### ISSUE TITLE
Skybox is visible through leaves

### ISSUE THREAD

**Issue by estradus** [HellFirePvP/AstralSorcery#10]
For some reason, the skybox keeps flickering to be visible through leaf blocks on and off (regardless of where the leaf blocks are or what angle i'm viewing them from - the transparency on them cuts straight through to the skybox) - giving them the impression of all turning blue and back to normal continually. I have no idea why or how this is happening; if its a problem with my graphics card or an incompatability with another mod, but Astral Sorcery is definetly the source of my troubles - the leaves function fine if I remove it.

It doesnt look like any mods I have might cause the issue - except for maybe better FPS? and I have no idea how to find my graphics card info.

**Comment by HellFirePvP** [comment]
I _do_ recall seeing this somewhere. It's basically you look at any block and it'll make leaves, uuh, more-transparent? I'm uncertain what's the source for this, however i do recall that this happened well back when i initially started with the mod - However, disabling the skybox render (and anything connected to it) entirely in my dev environment didn't lead to any change. I still blame this on Waila since i still have a version of that on my dev env and removing it fixxes the issue...

**Comment by HellFirePvP** [comment]
Try hiding your gui (with f1) when looking at a block. If that 'fixes' the issue it's _either_ connected to drawing the block bounds or an newly appeared overlay causes that. But well.. idk i'll further investigate, but i'm uncertain if i'm at fault or not. If adding my mod to it simply "makes it visible" doesn't necessarily mean the fault is on my end. It may be another mod at fault and it simply appears due to rendering i do.

**Comment by VallenFrostweaver** [comment]
If it helps - I don't use Waila, I use TOP (the one probe) and don't have this issue.

**Comment by HellFirePvP** [comment]
Could it be estradus that you're also using Waila by any chance?

**Comment by estradus** [comment]
Yeah I've got Waila - I'll double check this fix when I'm done with classes for the day.

**Comment by HellFirePvP** [comment]
I do suspect Waila being responsible for this. Even when disabling all my rendering, including all TileEntity, Effect and sky rendering & some minor other things, the rendering issue still persists. Removing Waila fixes that, so well, i do blame it being responsible for that.
