### ISSUE TITLE
Possible conflict with slashblade or random patches

### ISSUE THREAD

**Issue by kreezxil** [HellFirePvP/AstralSorcery#1024]
I player on a server of my World of Dragons modpack has reported an issue where Astral Sorcery **appears** to be implicated in the stack trace. I personally do not think it is, but I wanted to cover the bases and share the bug reported.

https://github.com/kreezxil/World-of-Dragons/issues/79

server crash report: https://pastebin.com/uWD0YQct

**Comment by Doomgull** [comment]
AS is in the trace because of the Resplendent Prism adding a compound tag to all non-stacking, non-enchanted book, non-potion items.

Might be the below since it's mentioned in the trace as well, but it may also be a red herring:  com.therandomlabs.randompatches.patch.NBTTagCompoundPatch.areTagMapsEqual(NBTTagCompoundPatch.java:83)

If it's during launch and not during play, you can find an explanation in #762 for what's going on, but it may not help trying to figure out what's going on. IIRC, last time slashblade was mentioned in context with NBT, it was because they were doing some odd-appearing stuff with it. Hope it helps.

**Comment by kreezxil** [comment]
The player said it happened during play. I also referenced all mods indicated in the trace.
