### ISSUE TITLE
Feature Request/Bug: 'Dynamic Trees' compatibility

### ISSUE THREAD

**Issue by Sweddy** [HellFirePvP/AstralSorcery#1027]
Hello,

I don't know if cross-mod-compatibility issues really count as bugs, but here it is. It has to do with the '[Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees?gameCategorySlug=mc-mods&projectID=252818)' mod.
When using the Infused Crystal Axe on a dynamic tree, the tree is properly destroyed but it drops nothing. Furthermore, the Tree Beacon is incompatible with dynamic trees.
I was wondering if compatibility on these regards could be implemented. I hope it's not too much of a bother.

Thanks.

**Comment by Doomgull** [comment]
Without yet digging deeply into the source, I'm going to say compatibility is likely impossible because they are doing special custom things for the trees, and not using "normal" tree methods.

**Comment by Sweddy** [comment]
Darn.

I know dynamic trees are definitely defined as trees though, because '[Minecolonies](https://minecraft.curseforge.com/projects/minecolonies)' NPCs manage to identify them as trees, but I don't know if that's relevant here or not.

**Comment by Doomgull** [comment]
Not particularly. The Tree Beacon listens for the growth event and intercepts it, triggering it's own variant instead, replacing the blocks the tree would have grown with using it's own ghostly version instead, and using the data to dispense drops.

So if they're using their own customer event for that (unlikely since it the tree would just grow normally), hooking something else (possible, but unlikely), or dynamically allocating what blocks should make up the tree using internal methods to dynamically shape/grow them (most likely based on a quick skim), there won't be any default data for the beacon to use to populate.

**Comment by Sweddy** [comment]
Ok. 
What about the Infused Crystal Axe consuming the trees without drops? Is that fixable?
