### ISSUE TITLE
Redstone ore breaks slow with infused crystal pickaxe, and multiblocks issues. v1.10.11

### ISSUE THREAD

**Issue by PeterGamesGR** [HellFirePvP/AstralSorcery#1028]
I used a mineralis ritual to turn stone into ores, but when I tried to mine redstone ores I realized that it was slow. I was using the infused pickaxe to break it, and when I tried using a diamond pickaxe it worked. Also,I had some issues when constructing multiblock structures. I had to relog for the enhanced crystal altars to work and I had to break crafting altars for the multiblock to form. Then I tried using the sextant in creative to build the structures and I still had the same issues. I was using version 1.10.11.

**Comment by Doomgull** [comment]
What mods did you have in total when attempting to mine the redstone ore?

Also, the multiblock thing is known, because attempting to make the system functional with Sponge without requiring a spongeforge patch has made the system less performant in its updates and caching, so sometimes you need to break and replace the main block after the structure is built.

**Comment by PeterGamesGR** [comment]
I used vanilla Astral Sorcery, baubles and jei.

**Comment by PeterGamesGR** [comment]
It was just a testing profile I made, so I could confirm the multiblock issues, and I also found this. In my modpack profile I thought the multiblock thing was a compatability issue.

**Comment by HellFirePvP** [comment]
https://i.imgur.com/2e1owbj.png

It's a mystery.

**Comment by HellFirePvP** [comment]
The redstone is fixed, multiblock i'll need to look at further regardless. marking it as fixed for now since the multiblock fixes might take a while longer.

**Comment by PeterGamesGR** [comment]
Nice!!! Keep up the great work!!!
