### ISSUE TITLE
Suggestion: Configurable perk effectiveness

### ISSUE THREAD

**Issue by SirAron111** [HellFirePvP/AstralSorcery#1032]
I have run into a small problem with astral sorcery. The perk system especially discidia and armara aren’t made to work with other mods doing things with HP/Armor and Damage.

For example when using scaling health Mod and using the perk that converts armor to HP you lose all the Scaling health HP and you are unable to add new Scaling health HP to your character (result less hp than before and 0 armor).

When using Tinkers armor that has super high armor values as they are adjustable with scripts. You can gain too much armor/toughness making you indestructible even for the chaos guardian who normally kills people in creative mode.

And lastly the most unbalanced aspect in combination with other mods would be the damage especially the extra melee/ranged % dmg perk nodes. As a modpack maker its hard to adjust the damage people are allowed to do when they have weapons that already do 60-100 dmg per hit and the perks get added to it they suddenly deal 300-400 dmg killing bosses with 5000 hp super fast.

Would it be possible to adjust these in the config? Like generalizing the small nodes so that with one config you can adjust all the small 5%melee nodes down to 2% or something like that! Or going away from the % and instead adding flat values? this would make balancing out damg and increased damage much easier for Modpack makers who want to use the astral sorcery mod and all its features without breaking the Modpacks balancing.

Also an item to remove a perk would be nice so that if you miss clicked you don’t have to reattune yourself fully new.

Thank you for reading this. Loving the Mod.

**Comment by Doomgull** [comment]
AS leverages the vanilla player attributes system. You would need to address this with whatever mod is doing the scaling of HP/Armor/Damage to determine how they are doing it, and whether they are doing it properly via attribute or just modifying the final value (which makes it incompatible with anything touching the system otherwise).

AS's Mantles already make the Chaos Guardian fairly easy to deal with, as they come with 80% chaos resistance in the first place and are configurable on that level of resistance from 0 to 100%. If someone does something silly with the config in any mod, that's on the pack author.

You can already configure the perk values, which ones exist, and how the connect since the new perk tree system released: https://github.com/HellFirePvP/AstralSorcery/blob/master/AS-Example.zs

That item won't be added, as it already exists in the form of the Iridescent Star and granular manipulation isn't something that's intended to be supported.
