### ISSUE TITLE
[1.11.2 - 1.3.0b] Liquid Starlight can freeze, and breaking it results in conversion into water.

### ISSUE THREAD

**Issue by GeekBeam** [HellFirePvP/AstralSorcery#105]
just...give it some time during a blizzard, and liquid starlight sources will freeze into normal ice. which breaking it will result in only water...thus making things that require liquid starlight out in the world are in danger of freezing over.

**Comment by HellFirePvP** [comment]
With only vanilla and forge, water being adjacent to liquid starlight source blocks will end up in the liquid starlight slowly being taken over by ice until completely replaced - which is not something that's un-intended. The adjacent source-blocks will melt the ice due to light, causing the -again- adjacent liquid starlight sourceblocks to freeze over. That'll chain onto all liquid starlight sourceblocks.

If no interaction between water & liquid starlight sourceblocks happens, the liquid starlight doesn't freeze over just by itself. Its light-level prevents it from being frozen and normally minecraft mechanics *only* (actually hard-coded to minecraft water blocks) freeze over water to ice.

IF liquid starlight source blocks should freeze just by themselves, i suspect a weather mod or related to add this since the liquid itself is *kinda* cold, so i can see weather mods assuming it's "cold enough" to freeze. Which would surprise me if a weather mod would just flat out freeze any fluid that's 'cold' into minecraft ice.

**Comment by HellFirePvP** [comment]
So uh. yea. not sure what else to say. Unless there's a mod involved that ignores the light levels and freezes any fluid (presumably other than lava, or sufficiently cold) into vanilla ice, the way i described above is the only way for liquid starlight to freeze over.

Not much else to add to this.
