### ISSUE TITLE
Tree beacons effecting things they shouldnt in ftb interaction

### ISSUE THREAD

**Issue by tyler489** [HellFirePvP/AstralSorcery#1060]
Like #439 im playing in the newest version of ftb interactions I'll get a version of astril sorcery when I get home

Blocks keep getting "selected" by the tree beacon. So far have seen Pam's fruit nodes
Ex2 Redstone clocks Minecraft levers Minecraft grass and a couple of other things. Server admins keep going around and using setblock to replace them with dirt at request ill attach a few pictures of the ones I have seen

**Comment by tyler489** [comment]
https://m.imgur.com/wh8ZkKn?r

**Comment by tyler489** [comment]
after talking with players some player dont even have any astral sorcery stuff including tree beacons. illumination wand is gated to far into the pack for anyone to have it at this time.

**Comment by HellFirePvP** [comment]
This strikes me as odd to be connected to the tree beacon.
The tree beacon picks up on something that is internally called "SaplingGrowTreeEvent" - basically an "event" that triggers when a sapling (most saplings, some mods don't fire that event...) grows into a tree. In specifics, _just before_ it would grow into a tree.

This being connected to that would reaise some interesting questions... even more so that it ends up actually only changing blocks to their translucent equivalents if they in their course of growing change at least more than 2 blocks. in addition to that, if the tree beacon it is supposedly linked to does not exist, it'll just revert to the original/non-translucent state of block.

So this is very weird to me. kinda.

**Comment by Saereth** [comment]
I will add some people that have this issue dont even have tree beacons at all they just login to find a redstone clock or something is identifying as an astral sorcery indestructible block

**Comment by Doomgull** [comment]
It sounds like something is triggering the block change outside of Astral sorcery

**Comment by Saereth** [comment]
https://www.youtube.com/watch?v=8bdm3gnfgDY&feature=youtu.be&t=88
^relevant

**Comment by Doomgull** [comment]
Since there is now debug for this, please advise if issue repeats with debug logging enabled.
