### ISSUE TITLE
[1.11.2-1.30-beta] Eclipse every day

### ISSUE THREAD

**Issue by Aphyxia** [HellFirePvP/AstralSorcery#109]
I'm getting eclipses every day. Starts slightly before midday and ends slightly after midday. Using the bed becomes possible during this time and it becomes dark.
Tested on forge 2266 and 2282 with only astral sorcery mod.

Is this intended? I'm really confused right now.

**Comment by HellFirePvP** [comment]
> Using the bed becomes possible during this time
This unintentionally works, i suspected vanilla had a better way of telling that it is night/day except looking for sky-light. but well. that's fixed/adressed now.

> eclipses every day
You're the first one to report this and i have no way of reproducing it or haven't heard of anyone that experienced this.. ? Unless there is some other mod screwing with your worldtime or using the bed during a solar eclipse resets it to the beginning of the day, i physically can't see a way for this to happen.

**Comment by Aphyxia** [comment]
Bit of backstory then. 
Before installing this mod  I used opticmanager mod to set daytime to 30000 ticks. Noticed the eclipses after installing this mod. Then I removed all the mods but astral sorcery and created a new world. Day lasted the normal time and eclipsed. I didn't wait for another day but deduced from that eclipses still happen every day even without mods.

**Comment by HellFirePvP** [comment]
There is currently the issue that on the very 1st day there will always be a solar & lunar eclipse. That's adressed in the next version though. So... yea.. creating a new world at the moment will cause you to see an eclipse the 1st day.

And AstralSorcery expects a worldTime of 24000 ticks/day. Anything that elongates that *will* cause issues as the ticks/day is nowhere clearly defined. Vanilla is hardcoded to 24000 everywhere..

**Comment by Aphyxia** [comment]
Is there any way to work around this or will I be forced to choose between longer days and astral sorcery?

**Comment by HellFirePvP** [comment]
*WELL* i can redo all of my sky calculations, all night/day related things and scan for everything that tracks and calculates fractions of days/nights throughout the whole mod, potentially breaking a ton of things in the process, to add a config option that allows you to say how long a day (on total; day + night) is. For the moment i'm not too keen on breaking more things of the mod, no. Besides, from the feedback i've got, more people want longer *nights* than days playing with AstralSorcery..

For mods that provide assymetric day/night time changes (day longer than night and that stuff) i would need to rewrite and adjust a few other parts of the mod to be compatible with that; So that will never happen either way.

**Comment by HellFirePvP** [comment]
However, the bug itself has been adressed, so for overview's sake i'm gonna close this for now..
