### ISSUE TITLE
+Maximum Life perks not sustained through Quit/Save/Reload

### ISSUE THREAD

**Issue by Moleculor** [HellFirePvP/AstralSorcery#1166]
Enigmatica 2: Expert v1.67, Astral Sorcery v1.10.19. 

After attuning myself to Aevitas and selecting a few 'Maximum Life' perks, I've noticed that any time I reload my world (save, quit, come back in), my food saturation levels start dropping rapidly and I start "healing" from damage I didn't have when I quit.

0. Select some Maximum Life perks.
1. Quit at full health, full food saturation.
2. Reload world.
3. Watch saturation levels drop as "damage" is "healed". 

Obviously, this may also affect other perks, may only apply to server restarts and single player, etc. 

On an unrelated note: What happened to the 'ancient ones', with all their astral power? If they had such power, where did they go? :P

**Comment by Doomgull** [comment]
#1017

**Comment by Doomgull** [comment]
Some more information about the "ancients" may be coming in 2.0...

**Comment by HellFirePvP** [comment]
While this is not technically a vanilla/forge bug, it's due to the health calculating the first time for the player way before i know what perks the player has and thus adjust health accordingly. this has been redone in 1.14, so... unlikely that i'm gonna touch this part of the code again in 1.12. sorry. :|
