### ISSUE TITLE
shooting star error

### ISSUE THREAD

**Issue by AGmukbooks** [HellFirePvP/AstralSorcery#1176]
https://pastebin.com/JD6vp8gx

crashing clients  when shooting stars spawn or go accross sky in weird way, not entirely sure.

the server does not crash.

**Comment by Doomgull** [comment]
Something is doing something unclean with data handling. Is this be replicated in single player?

There's several core mods I've not interacted with in that trace, but something is uncleanly messing with the data. If this is testable in single player, strongly recommend doing so by checking if it repeats without CreativePatchingLoader, MixinLoaderForge, or SecretRoomsMod-Core each, to see when it stops happening, since that's the likely culprit then.

**Comment by AGmukbooks** [comment]
will do. thank you.

**Comment by AGmukbooks** [comment]
this error was not replicated in singleplayer, removing the mods did not make it replicatable. i think this may have been a net code error, but i'm unsure that this helps.
