### ISSUE TITLE
1.12.2 Focusing starlight on inert blocks in the world can cause gratuitous amounts of lag

### ISSUE THREAD

**Issue by Buggy123** [HellFirePvP/AstralSorcery#1186]
MC version: 1.12.2
AS version: 1.10.19
modpack: FTB Interactions

Focusing starlight on inert, non-transmuting blocks (such as dirt, cobblestone, or air) will cause lag, with no apparent upper limit:
![image](https://user-images.githubusercontent.com/16315400/65193214-56c8a000-da48-11e9-92c0-8efe9b77e45c.png)

[Profiler report](https://cdn.discordapp.com/attachments/360899120917118986/608124838997131265/AS-Bug.nps)
[Modlist](https://pastebin.com/g3CCWBAV)
[Testworld](https://cdn.discordapp.com/attachments/360899120917118986/608464301002457102/TESTWORLD.zip)
[Twitch export](https://cdn.discordapp.com/attachments/360899120917118986/608467381857288202/1.zip)

I reported this on discord a while ago, but it was recommended that I make a github issue report, so I'm making one now.

**Comment by michaelPoul** [comment]
The issue is in https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/LightOreTransmutations.java#L120, when it looks through a recipe by iterating through the entire list. Since FTB Interactions has roughly 550 transmutation recipes, doing this per block adds up.
Changing https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/LightOreTransmutations.java#L39 to an ArrayList completely fixed the issue on my local build; I no longer see that function in the profiler. However I only have a few blocks with starlight, so it went from 0.2% of time -> 0. A hashset may be better.
[astral_before.zip](https://github.com/HellFirePvP/AstralSorcery/files/4017990/astral_before.zip)
[astral_after.zip](https://github.com/HellFirePvP/AstralSorcery/files/4017991/astral_after.zip)

**Comment by HellFirePvP** [comment]
I'm terribly sorry i didn't pay more attention to this sooner.
I did replace the linkedlist with an arraylist for now, so this should definitely help the situation.
