### ISSUE TITLE
[bug] Floating Crystal Crafting Table Recipes - Result Hidden

### ISSUE THREAD

**Issue by Tetrajak** [HellFirePvP/AstralSorcery#119]
Recipes for the crafting table under the floating crystal do not display their output in the crafting table GUI, but when clicking on the output slot the appropriate result is given for the inserted ingredients.

**Comment by HellFirePvP** [comment]
Known to happen together with mods that modify the crafting table gui. Not much i can do there besides adding special casing for tens of mods that change every version and are different between 1.10.2 and 1.11.2 - so i'd constantly be checking other mods and check every update they are making. Not going to happen. If there's a general solution to then i'm fine with it, but due to the nature of it, it doesn't look good for that.
