### ISSUE TITLE
Rock Crystal not splitting.

### ISSUE THREAD

**Issue by irondragon12** [HellFirePvP/AstralSorcery#1196]
so i have a size 400 purity 81% and cutting 100% and have used over 32 liquid starlight buckets to try and make it split but it still hasn't split.

**Comment by Doomgull** [comment]
Sounds like you need to check the config options for the pack you are playing, because while it may be possible RNG hates you _that much_, it is more likely that splitting is disabled in the pack you are playing. Check for the "canCrystalGrowthYieldDuplicates" setting.

Esp if you're playing FTB:Interactions.
