### ISSUE TITLE
Amulet trying to force compatibility onto the V-Pet from Digimobs

### ISSUE THREAD

**Issue by PikachuMC99** [HellFirePvP/AstralSorcery#1207]
So recently I made a pack for me and some friends that include AS along with Digimobs (the Digimon mod) and I found an issue that causes the game to crash whenever I right-click the V-Pet after looking at the crash log and asking the Digimobs discord it looks like its AS that is causing the crash.

Here is the crash report.
[crash-2019-12-02_16.16.57-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/3913768/crash-2019-12-02_16.16.57-client.txt)

Here is what Cyan (Digimobs creator) had to say about it
"The mod is trying to force a capability from the Amulet on to a v-pet, something that it cannot do. There's your crash. This isn't digimobs related, but it sounds like Tenza already has an idea of where your issue is."

**Comment by HellFirePvP** [comment]
Hard to say, since his source isn't visible.
This is usually due to someone fcking up on how to use capabilities. Keep in mind, capabilities are exactly made for this kindof use-case, to allow adding capabilities to OTHER ITEMS that are NOT from your own mod.
However, looking at it from a glance, seems like he's calling getCapability with 'null' as a capability, thus causing an capability.equals() to fail on my end. https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/AmuletHolderCapability.java#L73
This issue is on his end, as you are to ensure to never pass 'null' as a parameter that's annotated as nonnull. Whether he now wants to believe that or not, this isn't something that i can fix here as it's not my fault.
