### ISSUE TITLE
[feature] Rockcrystal ore generation integration with other mods

### ISSUE THREAD

**Issue by LemADEC** [HellFirePvP/AstralSorcery#1209]
As of 1.12.2-1.10.20, rockcrystal ore generation doesn't integrate with other mods:
- it won't work in the TwilightForest 1.12.2-3.10.1013, neither with default configuration nor while whitelisting 7 and DIM7.
- using another mod like CoFH World to workaround this issue won't be registered by the resonating wand.
- overworld generation appears to be incompatible with UndergroundBiomesConstructs-1.12-1.3.7, unlike other mods doing ore generation. I wonder if AstralSorcery is generating ores too late, after UBC replace stone with its own variant.

**Comment by Doomgull** [comment]
Can you clarify the twilight forest line?

Using another mod's ore generation to place and register the locations of the ores for location via the Resonating Wand would require a rework of the system to do so in a performant manner. This is known, and won't be changed in 1.12 releases. It may not change in 1.14 yet, still undecided.

Is there a crash log for UBC?

**Comment by HellFirePvP** [comment]
You can go into the config, the rock crystal's configuration section, and add states to "ReplacementStates".
All blockstates listed there are eligable to be replaced by rock crystal ore for ore-generation.

So if you suggest it doesn't generate because there's not enough stone, consider adding your current blockstates that are generating in your world to that list so it recognizes them as eligable/disposable to be replaced by the rock crystal ore.
With regards to the worldgen, add the dimensionId to the "DimensionWhitelist" for the rock crystal ore feature, as well as into the 'global' whitelist of "worldGenWhitelist".

**Comment by LemADEC** [comment]
1- Adding Twilight Forest dimension id (7 & DIM7) doesn't solve the issue: vanilla stone is still not replaced with Rockcrystal ore. The ReplacementStates already contains minecraft:stone:0 by default.

2- I understand resonanting wand won't be fixed on 1.12.2 and since the ticket was closed, it is unlikely to be fixed on 1.14.4.

3- There is no crash with UBC, it simply doesn't generate the rock crystal ores.

**Comment by HellFirePvP** [comment]
As i said, there's 2 whitelists. one for generally all worldgen, one specific for rock crystal ore.

**Comment by LemADEC** [comment]
As I said, both are configured and still not generating in the Twilight Forest.

**Comment by HellFirePvP** [comment]
shrug
guess it doesn't work then. Code exists and is known to be functional; not sure what TF does differently.

**Comment by LemADEC** [comment]
Can we reopen the ticket so it get fixed then?

**Comment by Doomgull** [comment]
It works in active modpacks using other dimensions. This would need TF to look at what they are doing that is different. Or maybe spongeforge.

**Comment by LemADEC** [comment]
All 3 issues were found in single player without SpongeForge.
In fact, you only need TwilightForest and AstralSorcery to reproduce the first issue.
To my knowledge, AstralSorcery is the only one having issues with generating ores in TwilightForest or being incompatible with UndergroundBiomes.

**Comment by Doomgull** [comment]
Because rock crystal ore isn't a registered ore. So "normal" ore methods don't interact properly. The replacement generation isn't through errors in testing, but skimming through TF code, it looks like they take control over most of that anyway. They added an IMC feature earlier this year for ore gen compat to add ores in the first place, but seeing as how rock crystal ore isn't actually an ore, but a separate worldgen feature...

Again, talk to TF about it, or add it via one of their supported methods and accept it won't show to the resonating wand.
