### ISSUE TITLE
[Suggestion] Make Faint Amaranth be a pottable plant

### ISSUE THREAD

**Issue by shroomdog27** [HellFirePvP/AstralSorcery#1230]
It would be really cool to be able to put them in a pot to have as decor inside of a base! I know it's kinda useless, but I still think it would be nifty.

**Comment by HellFirePvP** [comment]
Been a while since this was made, so, better reply late than never:

The constants for what can be potted and what can't are hard-coded in 1.12's minecraft flowerpot. Ultimately, to make this pottable, this would need to be its own block with its own rendering. As it stands, i'll mostly focus on fixing bugs and adressing pressing issues with 1.12 and focus on new features for 1.14+
