### ISSUE TITLE
Progression reset

### ISSUE THREAD

**Issue by Tanzerr** [HellFirePvP/AstralSorcery#1264]
Everytime i get out of mc and then log back in to get into my world, im gifted a new book and all my astral sorcery data is reset even though i had already unlocked most of the book.

**Comment by Doomgull** [comment]
Either your player data is corrupting on world exit (how are you exiting MC? Is it by clicking the red X to close the window instead of using the exit button to gracefully close?), or the location the player data is being stored doesn't have sufficient permissions to update the player.astral file's progress. This is either operational, or environmental.

**Comment by Tanzerr** [comment]
i use the exit button to gracefully close yet nothing changes. I have also used the red X to close the window but this was while the issue was present. For your second point, I have looked into player data and where the information is being stored and it seems to be fine however i'm not sure on how to check whether there is sufficient permission to update the progress

**Comment by Doomgull** [comment]
(assuming windows) right click the directory and the player.astral files and select Properties and make sure they aren't marked Read Only. Only way you won't retain progress and it treats you like you're a new player every time you log in is if the .astral file isn't allowed to update, or unless your player ID changes every time (like if using a cracked launcher) instead of being tied to a legit minecraft account.

**Comment by Tanzerr** [comment]
Thank you very much!
