### ISSUE TITLE
[Suggestion] Sigil upgrade, Wands, Rituals, and expanded knowledge

### ISSUE THREAD

**Issue by Brillik** [HellFirePvP/AstralSorcery#1265]
I've come up with a few of ideas which might improve some quality of life issues, and if it'd be better to edit this into multiple suggestion threads, I'd be happy to do that:
1. what if you could upgrade the sealing sigil to a toggle sigil which would allow you to turn an ability on and off without having to replace the seal each time? A comet colored check mark, or versus a bright red to identify the two. 
2. There's a number of wands available and while they are all amazing, what if we could setup a small ritual using starlight from a crystal onto some relays holding each wand to combine them together, and allow you to switch between one wand to another with a shift-click, or keybind, then you could have a resonating wand or attuned wand, illumination wand, formation, conversion and impulsion all in one space. A similar but more complex ritual could be used to change out the attuned gem found in the center of each mantle - so that the intrepid sorcerer doesn't need to sacrifice inventory space to carry a mineralis, vicio and fornax mantle around
3. A ritual using a collector crystal aiming starlight at 5 -6 prismlenses creating a sort of spiderweb network which could attune your resonating wand to allow you to catch falling stars when you came within 9 blocks or so from them. This would allow skyblock users to have a chance to catch them provided they had a sort of flight/glide and could get close enough before the star fell into the void. Alternately, the spiderweb ritual could simply attract the falling stars providing a location for them to fall so long as the viewer maintained a constant vigil on the star as is currently done.
4. What if we could expand our limited astral knowledge and gain additional levels beyond the level 30 cap for each dim and faint constellation charted? Opening shining casings could also provide this increased opportunity for astral knowledge up to the level 100 cap.
5. One of the biggest aspects of real life astronomy is knowing the phases of the moon, and something that might be very helpful is an in-game calendar of sorts which would not only display the phases in an astral sorcery sort of manner, but also indicate when the next solar eclipse is set to happen.

**Comment by yagoplx** [comment]
I think the constellations the Shining Casings create need some tweaking as well - getting the casing and then discovering the constellation is not exactly a piece of cake, and the only reward is an unlocked lore entry.

These constellations should make the sorcerer discover not one fact, but (have a chance to) discover more as well. Or else it would take forever to unlock all the entries. (or is this already how it works?)

**Comment by Doomgull** [comment]
1. Not intended. There's a key toggle for many of the active perk abilities in 1.15+ however.
2. Not really an issue in 1.15+ because of some collapsing of gear, but mantle choice is part of the mechanics.
3. Lucent scrolls aren't a thing in 1.15 or later releases anymore. Building out a platform to catch the stars in prior versions is the recommendation. The knowledge is also not specific per world, but is global (pre-1.15 where the hidden knowledge is removed), and so any unlocks in other packs still retains that knowledge in skyblock.
4. The level is already configurable up to 100, it will not go above that. Custom items that grant perk points are also already supported in the code.
5. On the master "No" list.
