### ISSUE TITLE
Shader Incompatibility 

### ISSUE THREAD

**Issue by TitusArmillius** [HellFirePvP/AstralSorcery#13]
When running this mod with a shaderpack, it will cause various lighting/sky issues.

I tested with Chocapic's shader v6 through installing and uninstalling to see if there is a difference.

Try out a shader to see what I mean.

I suspect you might change some graphical files shaders relies upon.

**Comment by HellFirePvP** [comment]
Figured as much after the incompatibilities with StellarSky. Will look into it again~

**Comment by HellFirePvP** [comment]
Adressed by the addition of 'weakSkyRenders' config option in 1.1.4+

For clarification: It will, if that's enabled for the given dimensionID, instead of rendering the whole skybox, render just the constellations on top of the existing skybox.

This is compatible with shaders & stuff so i suspect it's compatible with whatever stellar sky does.
In case it is not, just reopen this issue.
