### ISSUE TITLE
Resonant wand, does not want to highlight ore

### ISSUE THREAD

**Issue by Mammer-Rus** [HellFirePvP/AstralSorcery#1300]
I ran into a problem. I can not find rock crystal ore. What I did? I made a resonating wand, went looking in the world, but after flying several thousand blocks, I did not find a single glow. Taking the ore from the creative, I put it underground and again took the rod in my hands and again there is no glow. Because of what it may be, or there have been some changes that I can not find.

**Comment by Doomgull** [comment]
It only shows ores placed during world generation by this mod, because no other mod ties into the location cache to mark positions that should glow.

Double check that oregen is being handled by this mod in the configs, and that you didn't delete or modify world files.

This would be better served through the discord, as this is more of a help issue than a bug.
