### ISSUE TITLE
[1.15.2] Config option to disable marble generation

### ISSUE THREAD

**Issue by TheUntamed** [HellFirePvP/AstralSorcery#1317]
Can you add a config to disable the generation of marble?

**Comment by HellFirePvP** [comment]
Theoretically speaking you can set the biome-restriction for marble to whitelist instead of blacklist ("whitelistbiomespecification") and remove all applicable biome-types from the biometype list ("biometypes") to achieve the same effect.

Though that is not trivial to see at first glance, so, yes, this straight-forward option will be included in the next build.

**Comment by TheUntamed** [comment]
I don't even see where I can set the biome black/whitelist for marble. For The structures and ores I can see it but not for the underground generated marble.

**Comment by HellFirePvP** [comment]
Right.. derp. :|
Yea, i'll tackle this in the next update.
