### ISSUE TITLE
Resplendent Prism not working

### ISSUE THREAD

**Issue by nailfor** [HellFirePvP/AstralSorcery#1398]
astralsorcery-1.12.2-1.10.27.jar

i have Prism with minecraft:silk_touch 
https://media.discordapp.net/attachments/559331114909564948/759216366401224714/Screenshot_20200926_035419.png?width=400&height=268

My stone pickaxe just break the glass. 
I also tested mending - no effect on pickup orb of exp

**Comment by yagoplx** [comment]
Is this a bug, really? I thought the intended behavior of the Prism is to increase the level of existing Enchantments, not to give these enchantments to tools where applicable. This means that leveling up Silk Touch is pointless, since it is a single level enchantment, and you should be re-rolling the Prism when that happens (which is fine). I can see that the stone pickaxe in your hand is not glinting with enchantment, so it is technically working as intended.

Imagine if the Prism actually could apply Silk Touch to any held pickaxe, and you ended up with both Fortune and Silk Touch on them. I'm sure that would cause some level of weirdness.

**Comment by Doomgull** [comment]
Yes, it's a bug. It's "+1 to <enchant>", not "+1 to existing <enchant>".

**Comment by yagoplx** [comment]
I totally did not see that 😶

Still unsure of what would happen if you let conflicting enchantments combine, hopefully there are checks and it covers enchantments that other mods may mark as incompatible with one another

-------- Mensagem Original --------
Ativo 11 de dez de 2020 1:09 AM, Doomgull escreveu:
