### ISSUE TITLE
Shader support

### ISSUE THREAD

**Issue by Deadder** [HellFirePvP/AstralSorcery#140]
Hey there,

Definitely a feature request here - 

Any chance there could be some shader support? Specifically with the particles?

We can work around the texture bleaching/reflecting issues - but the particles are literally crash inducing with some shaderpacks.  Basically, if you have time - I know there are are a few of us that would GREATLY appreciate it! 😃

**Comment by Doomgull** [comment]
Check closed issues #124 and #13.

**Comment by HellFirePvP** [comment]
To maybe leave this in the correct issue:

> Thanks for the response @HellFirePvP !
I already found the weakSkyRenders option and it is set and the sky works as intended - which is awesome!
However, that is not what I am referencing - particles are the issue. If you set down, for instance the tree beacon the particles distort the entire area and parts just make the world transparent when looking through them with a shader pack installed. Like i mentioned above the rest of the mod works in sharder packs with a little tweaking - except particles. I can try to grab a screenshot tonight if that helps.

Well i suppose my particle system doesn't support shaders since it's vastly different from the vanilla system that wouldn't really support particles and effects the way i need them to be... Adding support for that might not be trivial and/or easy to do. I'm gonna look what i can do but i will not make any promises or related.

**Comment by Deadder** [comment]
@HellFirePvP totally understand.  Just wanted to mention it and at least start a conversation on it.  Obviously, if you start digging into it and its going to take a ton of time no one is going to blame you for skipping it.

Appreciate the research regardless of the outcome!

**Comment by HellFirePvP** [comment]
Alright i'm going to conclude my state on this:

i'm not going to sink a few days into this to make it compatible with a bunch of the shaders and have it crash with the rest. i'm afraid that in order to make it work, i'd need to trick it into believing that these are vanilla particles and as a result it's going to be a bigger stability issue than it currently is for the tradeoff of having it work with a certain few.

If i can come up with a better solution in the future, i'm certain to potentially add support, but for now i'm gonna give it a solid "no", sorry.

**Comment by Deadder** [comment]
@HellFirePvP That completely makes sense.  I appreciate you taking a look!  I have been messing with some shaders and i am tweaking some of the GLSL code and things are starting to look better - so I can at least work around it.  Thanks!
