### ISSUE TITLE
The Domic Resonator shows the ritual range in the wrong spot when the ritual is transposed with an anchor

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1492]
1.15.2-1.12.13
The Domic Resonator doesn't show the range of a ritual in the spot it's actually in, when the ritual has been moved with a Ritual Anchor.
Also you can't use the Domic Resonator on a Ritual Anchor to see its actual range.

**Comment by HellFirePvP** [comment]
I'm not sure this is fixable without a large transfer of a lot of data and constantly keeping the client up to date about something that happens in potentially unloaded chunks.
The client might not have the data about the ritual that happens at all.
So at the moment i will shelf this enhancement due to the amount of work needed. i'll keep it in the suggestions list though.
