### ISSUE TITLE
Search: Home key moves true caret but not visual caret

### ISSUE THREAD

**Issue by andrewsf** [HellFirePvP/AstralSorcery#1501]
When using the search feature of the Astral Tome, the visual caret is always at the end, even when the edit position is not. This misleads players about what effect their behaviors will have.

# Versions
Astral Sorcery: 1.13.1
Minecraft: 1.16.4
Forge: 35.1.4

# Steps to reproduce

1. Open Astral Tome
1. Click to search bar
1. Type `abc`
1. Press the Home key on your keyboard
1. Type `123`

# Expected behavior

Either:
* Text will show `123abc`, and the insertion caret will visually show between `123` and `abc`.
* Text will show `abc123`, and the insertion caret will visually show at the end, after `abc123`.

# Actual behavior

Text will show `123abc`, and the insertion caret will visually show at the end, after `123abc`.

The misplaced cursor gets even more confusing if you close the Astral Tome, open it again later, and try to use Backspace to remove your search query.

**Comment by HellFirePvP** [comment]
For the moment i will remove this feature as it'd also mean redoing a bunch of the rendering around text inputs.
Since it's "short" text input and not longer text that'd require quick navigation around big blocks of things, i don't consider it a critical feature right now. This might see full implementation in 1.17 when GUI things in minecraft get more streamlined.
