### ISSUE TITLE
[1.15/1.16] Astral Sorcery particle rendering breaks Nature's Aura particle rendering

### ISSUE THREAD

**Issue by incomingnerd** [HellFirePvP/AstralSorcery#1519]
**Problem**
Astral Sorcery triggers a rendering bug with Nature's Aura particles, resulting in them appearing as untextured quads. This has been reported to Ellpeck and I'm reporting here too as requested. See https://github.com/Ellpeck/NaturesAura/issues/165 .

**To reproduce**
1. Create an MC 1.15 or 1.16 instance with both Astral Sorcery and Nature's Aura.
2. Start a new Creative world.
3. Grow an ancient sapling and place an Astral Collector Crystal next to it.
4. Observe the broken square particles.

**Versions**
MC 1.16.4
Forge 35.1.7
Astral Sorcery 1.13.1
Nature's Aura 33.1

**Comment by Ellpeck** [comment]
I've never had an issue like this happen, but I also know that the particle system in Nature's Aura is, uh, outdated. I'm pretty sure that I don't have any dangling GL contexts though.

**Comment by HellFirePvP** [comment]
Please use RenderTypes for particles @Ellpeck
The issue here is most likely that the texture-state is not enabled and no valid texture is bound. Alongside potentially other defaults which would be set through a RenderType's setup.
If you need/want more specific instructions or examples, feel free to shoot me a dm on discord and i can go over things.

**Comment by HellFirePvP** [comment]
Ideally fixed with BlueAgent's PR on NaturalAura's side.

**Comment by HellFirePvP** [comment]
Fixed with the merging of that PR into NaturesAura.
Closing this on my end.
