### ISSUE TITLE
Latest build of SpongeForge on 1.10.2 + This mod = Crash

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#158]
https://pastebin.com/smWUXG04

https://github.com/SpongePowered/SpongeForge/issues/1491

**Comment by Sunconure11** [comment]
It turned out to be some corrupted data, but I'll leave this open anyways, just in case something else can be gleamed from the error.

**Comment by HellFirePvP** [comment]
file handling gets some additional safety mechanisms to prevent this from happening. If data is unrecoverably lost, i can't do much about it...

Unfortunately, this happens if it's in the middle of writing the data to the file while the server crashes or similiar. It's stored inside a directory in the world's directory so it *should* get backup'd when creating a world backup.

Regardless, this is most likely adressed as of next version.
