### ISSUE TITLE
Crash on load-in to world, heavily modded

### ISSUE THREAD

**Issue by Zainyest** [HellFirePvP/AstralSorcery#1591]
Game version: 1.16.4
Mod version: 1.13.8
Forge version: 35.1.13
Crashlog:
https://pastebin.pl/view/42d5a6c3

**Comment by HellFirePvP** [comment]
After going through the modlist and checking mods for a while, i didn't immediately find an offendor.
I'd recommend removing mods and checking if it works with a smaller set and thus narrowing down which mod it could be.

**Comment by Zainyest** [comment]
Hi! I just found the mod conflicting, it was C.O.M.B.A.T., and I was having other issues performance-wise with that mod so it is definitely the problem. Might be some sort of GUI conflict, as it was doing weird fps drop issues that depended on if you were in an overlay or not.
Mod: https://www.curseforge.com/minecraft/mc-mods/c-o-m-b-a-t

**Comment by HellFirePvP** [comment]
From the looks of it, that ASM patch seems outdated as their debug-output suggests they're at the wrong place when they're injecting their patch.
Additionally, their assumptions about the current stack at the place they're patching things into are incorrect and thus result into wrong values being left on the local stack, thus resulting into the stack having wrong variables stored, leading to the crash described above.

Unfortunately, this is a issue combat needs to fix.

Additionally, combat discards whatever manipulations to entity reach have been done, so with combat installed, AS' entity reach wouldn't even work due to the implementation of their patch.
