### ISSUE TITLE
[Issue] Unable to interact with the Starlight Infuser with Fake Players

### ISSUE THREAD

**Issue by MuteTiefling** [HellFirePvP/AstralSorcery#1596]
Version : astralsorcery-1.16.4-1.13.8

The Starlight Infuser no longer appears to be automatable, which seems like rather a shame since it's such a useful system for material processing. 

![2020-12-25_21 18 15](https://user-images.githubusercontent.com/9543430/103144399-b8b99000-46f6-11eb-9b9b-bf30e83e38c1.png)

In the screenshot above, I'm attempting to place diamond ore into the infuser with a fake player, which works just fine. I then use that same fake player (drone from Pneumaticcraft) to attempt to right click with the Resonating Wand, which fails to trigger the craft.

I've also attempted this with simple right click machines (Modular Routers) place directly against the Altar. They appear to have the same issue. They can place items in the Altar, but cannot trigger the craft with the wand. I can confirm that the presence of this block does not interfere with the multiblock in the slightest, as I can still manually trigger the craft with it present.

**Comment by HellFirePvP** [comment]
Due to the rewrite towards 1.15+ the infuser recipes also got reworked and are now tied into the progression-checks that are done if a player is able to craft something, thus now checking the player that is trying to start the recipe if they have the needed progression. Which won't work for fake players unfortunately.

As it stands this is indeed the 'status quo', however i do have a solution lined up for AS v1.14.0

**Comment by MuteTiefling** [comment]
Ah, that's good to hear. I really love this mechanic, but it's of limited use for things like ore processing if it cannot be automated.

**Comment by Verisimilitu** [comment]
Just a quick follow on question to the above - is this behavior intended to work for all of Astral Sorcery's blocks? I ask this because of any kind of fake player being unable to interact with the lightwell (At least that my friends and I can determine), but if this is still intended and there's a solution planned, I just wanted to make sure.

**Comment by welch3694** [comment]
Yeah, having the same issues as Verisimilitu, it's not possible to automate the production of liquid starlight, as I cannot get any fake player to interact with the Light Well with Aquamarine.

That combined with the inability to automate using a resonating wand on a Starlight Infuser really makes this not an option anymore.

You mentioned there's a solution for 1.14 of Astral Sorcery, just curious if there's any details?

**Comment by PocketfulOfGeese** [comment]
"When it's out, you'll know" are the details at present. Real life is occupying Hellfire's time considerably, and there's a lot of stuff going on in the background. This is an incredibly low-priority task at the moment, and will have alterations for 1.14 whenever that releases.

**Comment by HellFirePvP** [comment]
Will close this for now.
The feature is still on the table, but. yea. delayed since other things happened in life and my plans for AS got a bit pushed back. Will be added eventually, but for now "intended" to be the functionality - or rather that it doesn't work atm.
