### ISSUE TITLE
Horologium / Solar Eclipse

### ISSUE THREAD

**Issue by kienee** [HellFirePvP/AstralSorcery#1632]
Hey,

I've been playing the newest version of Direwolf20 1.16 FTB Pack and started to get in to Astral Sorcery. Currently im on day 600ish (MC day) and checked every day for an Solar Eclipse and mostly every night for horologium but somehow i cant seem to get it with the telescope.
Is there a bug or is it just my bad luck?

Thanks in advance

**Comment by HellFirePvP** [comment]
Depends.
If you have the skyrendering disabled or added it so it only renders the constellations instead of the full custom skyrendering, in case you want to play with shaders, you don't really get to see the solar eclipse as it is, well, rendered in the custom sky rendering.
I'd suggest it was bad luck as a lot of people did indeed find it - including DW20 himself on video.
