### ISSUE TITLE
[Mod Conflict] Can't link crystal to lens when Buildcraft 7.99.3 installed

### ISSUE THREAD

**Issue by titantwoshot** [HellFirePvP/AstralSorcery#165]
https://pastebin.com/NExMQBb4

**Comment by HellFirePvP** [comment]
As it says in the crash: Provide more information please.

Does it consistently happen? Like. create a fresh SP world, place a lens/prism/any-network-component down. Does it instantly crash afterwards? Does it only happen in MP worlds or also in SP? Is it *specifically* buildcraft or is it with another mod? Was this a previously created world and you updated AS to it? Did you have 1.4.0 AS on there and updated buildcraft and it now suddenly crashed? Have you moved the lens by any unusual means (aka bloodmagic transposer or anything else that unnaturally moves blocks)?

**Comment by titantwoshot** [comment]
Tested in a SP flat world with only Astral Sorcery 1.4.0 and Buildcraft 7.99.3 installed
It won't crash the game, but can't link between crystal and lens, prism. I tested it with ATM2 modpack it work perfectly when i removed Buildcraft

**Comment by kingofrunes** [comment]
Experiencing the same issue with Buildcraft 7.99.3 installed. No crashes, just refuses to link. This is happening on the Server and on Singleplayer. This world was created in 1.11 and AS hasn't been updated since it's been created. Lense hasn't been moved by any block movers. Removing buildcraft allows me to link the floating crystal with the crystal lens/iron ore. Putting it back in prevents it from linking :(
