### ISSUE TITLE
[1.16.4] Structures do not generate in non-default worldtypes (amplified, caves etc)

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1659]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/948

Structures do not generate in non-default worldtypes, such as amplified, caves.

Tested using the `/locate astralsorcery:ancient_shrine` command and flying around in spectator mode.

### Versions
- Forge-1.16.4-35.1.37
- astralsorcery-1.16.4-1.13.9

**Comment by jezzballin** [comment]
Hello, I am also having this issue with the same Forge and Astral Version in a Pre-Genned world.  I am going to freshly regenerate the (standard gen) world with the seed # and paste the old chunks in with MCASelector, and I'll update this comment with the results, but I wanted to chime in with this similar issue rather than creating a new one!

**Comment by jezzballin** [comment]
Just checking back in, regenerating the world with the same seed # and pasting the saved chunks back in with MCA Selector spawned Astral Structures as they are intended!

Just as an update: it seems Astral Sorcery needs to be present during the initial worldgen for structures to generate.  Ores generate as normal, but it seems like structures won't spawn unless AS is present during worldgen (on first startup)

**Comment by Angular-Angel** [comment]
Yeah I'm getting this bug in Enigmatica 3.13. Can confirm, no Astral Sorcery structures.

**Comment by HellFirePvP** [comment]
Wasn't added to the respective noise generator layers.
