### ISSUE TITLE
Celestial Gateway doesn't show 'remnant images'

### ISSUE THREAD

**Issue by nnystyxx** [HellFirePvP/AstralSorcery#169]
According to the journal entry for the Celestial Gateway, "Once a gateway has linked with a destination the first time, remnant images of that place will remain for future observations." I presume this means once a 'pad' has teleported you to another, the original will show you a preview of the place you're about to go to, but I can't seem to make that preview appear under any circumstances.

I stare at the star, in the right alignment to teleport (can hold right click and make the star swirl effect occur), but no image appears. Do I need some other item or condition for this to occur? Was this dummied out? Does the feature not work on 1.10.2?

EDIT: Apparently, this does -kind of- work, but the image is very small (limited to the original circle of stars) and disappears as soon as I release right click, leaving a tiny window of time to see the preview.

**Comment by HellFirePvP** [comment]
Well, as you've said, it *kind of* shows the images. the design is far from polished, i admit that without any hesitation, but i don't really want it to fade-in just by looking at the corresponding star.. that feels a bit odd. the advantage i have to only show it during focus is that the image doesn't look toooooo terribly out of place. normally it looks terrible since it's a full rectangle - because it's basically a screenshot - so showing that just when you hover over the star looks - even with only 10% transparency - already extremely terrible. Spherical scissoring to make it 'round' seems computationally very expensive to do so i'd like to refrain from doing that... I'm still in the process of refining its UI, so (non-troll-ish) suggestions are very welcome on that end.

**Comment by wizard1399** [comment]
I think the mod [Looking Glass](https://minecraft.curseforge.com/projects/lookingglass) had an api that was used to render views of other dimensions. Maybe you could find some inspiration or a few tricks to make what you are trying to do work.

**Comment by HellFirePvP** [comment]
No. will not do that for this.

**Comment by robertmaxton42** [comment]
Maybe you could have two controls? When I saw "focus" I assumed the shift key at first, that's the usual alt-look button, so maybe play off of that - shift to see your destination, and then you can't jump from crouching so it's obvious that the next command has to be right-click.

**Comment by Doomgull** [comment]
What if it was handled like the Ender IO block? While focused at the destination the black starfield behind it faded into the picture from Black Starfield -> Actual image, so it looked like the destination was becoming more "real" until you were actually there, no clipping the image out? I have zero concept of how computationally oppressive that might be on the client.

**Comment by Seth0067** [comment]
You may want to consider adding info to the portal preview that is more iconic in nature, maybe there's icons/glyphs to represent biomes and/or dimensions, or you could consider adding x/y/z info. 
 In general,there may be other ways to get players the location they are looking for without a preview shot. 

Another thing that occured to me is letting the player select/frame the preview image somehow as that may let them select visual elements that would help them remember each location (or if they want to be super-blunt, have a sign be part of the preview).

**Comment by Doomgull** [comment]
Consolidating into #495 due to age.
