### ISSUE TITLE
[1.1.2] Recipes as shown in the journal are rotated oddly, showing some incorrect recipes as a result

### ISSUE THREAD

**Issue by Febilian** [HellFirePvP/AstralSorcery#17]
I tested with literally nothing installed but Astral Sorcery, JEI, and Forge, and it's still happening, so hopefully this report is more useful than my previous one.

At first I thought the recipe for the wand had changed somewhat between the first released version and this one, but the 'new' recipe as shown in the book didn't work, and the one I recalled from before - which was rotated differently around the crafting grid - still worked.

Looking at what recipes I can in the book in a newly-created creative world, it seems that every recipe is rotated in this way if it's discernible.

Examples:

https://gyazo.com/41d439c08953cd27e2dc2d86be4793a8

https://gyazo.com/ceb5e15188ed9a3a9dc46c19f19ae433

**Comment by HellFirePvP** [comment]
Ugh, i know where that came from.. i'm retarded.. - this will be fixxed...

**Comment by MasterFee** [comment]
Recipe for Ritual Pedestal is rotated as well

**Comment by HellFirePvP** [comment]
Yea i suppose all of them are mirrored by an axis that goes from top left to lower right as a line. (if you can imagine that line as a mirror and - well - mirror from it)

This was caused by me being utterly retarded and not double checking things after fixing an indexing issue correlated to the fix for #11
