### ISSUE TITLE
Skybox Rendering Broken Again Try

### ISSUE THREAD

**Issue by SkullHunter55** [HellFirePvP/AstralSorcery#1726]
I currently have my config setup like this and I cant see the constellations on my resource pack skybox, when adding the id to both it also won't work...

#If a dimension is listed here, the skyrender will only render constellations on top of the existing skybox.
skyRenderingConstellations = ["minecraft:overworld"]

#Whitelist of dimension ID's that will have special astral sorcery sky rendering
skyRenderingEnabled = []

AND BEFORE YOU CLOSE IT AGAIN
even without any texture pack on these settings won't work, no clue what your settings are but it doesn't work on mine or any of our coders pc's

**Comment by PocketfulOfGeese** [comment]
1. Don't open dupes. Reply in the same ticket, it isn't locked.
2. It's a "best effort" option for unsupported instances. It works on many people's PCs in the community just fine, because that's exactly what it is: best effort. Conflicting anything with shaders runs that risk. If you're not using a shader, there's zero reason to touch these configs.
3. And, again, as in #1724, both options should read = ["minecraft:overworld"] for this in the overworld, because that's the dimension ID.
4. Discord is where you should be going for tech support or questions, this isn't a bug.
