### ISSUE TITLE
BC problem

### ISSUE THREAD

**Issue by 3269199948** [HellFirePvP/AstralSorcery#1774]
When I was using this mod, I was off waterfall -> Paper (Login Server) - BBB>X and I couldn't get into the Login Server, he told me

**Incomplete server tags, disconnecting. Missing**

why？When I use other mods, that's not the case

If so, I cannot join my login server

**Comment by PocketfulOfGeese** [comment]
No clue, but sponge/paper/etc isn't supported for use with the mod.

Forge env only.

**Comment by 3269199948** [comment]
> 没有任何线索，但是不支持将海绵/纸/等与该模块一起使用。
> 
> 仅伪造环境。


This is not an environment issue, I need to get into the login server before I can get to my other servers, but I can't get in

This problem did not appear in 1.12.2

**Comment by PocketfulOfGeese** [comment]
Lot of things changed since 1.12.2. Including Paper being created.

Support for non-forge-only environments has never changed, and has always been this mod's stance. If the waterfall plugin or paper team can show where something is not being performed properly per forge, it'll be looked at, but otherwise no.

**Comment by 3269199948** [comment]
> Lot of things changed since 1.12.2. Including Paper being created.
> 
> Support for non-forge-only environments has never changed, and has always been this mod's stance. If the waterfall plugin or paper team can show where something is not being performed properly per forge, it'll be looked at, but otherwise no.

Well, then I have to remove him, because there is nothing I can do now
