### ISSUE TITLE
Some AS item dups when Cardboard Box is used on the chest they are in.

### ISSUE THREAD

**Issue by Sunekaer** [HellFirePvP/AstralSorcery#1805]
Place a chest 
put any of these items in the chest:  Starmetal Ingot, Constellation Paper, any crystal, any celestial crystal
click Cardboard box from Mekanism on the chest and see the items getting dropped on the ground but they all still stays in the box .
these are the only items from AS or any mod that I could get to duplicate this way

Forge 36.1.4
mods\astralsorcery-1.16.4-1.13.9.jar
mods\Mekanism-1.16.5-10.0.21.448.jar

**Comment by Jeuvke** [comment]
Most likely a forge bug with custom item entities. See https://github.com/HellFirePvP/AstralSorcery/issues/1682#issuecomment-792276319

**Comment by HellFirePvP** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7785

**Comment by pupnewfster** [comment]
For reference we have worked around this in https://github.com/mekanism/Mekanism/issues/7053 (though the give issue definitely seems to be a thing). The issue was initially caused by https://github.com/MinecraftForge/MinecraftForge/commit/72d05d17a92b7060d6262d9553f4b7d5d6bc0a8f which delays the custom item entities by a tick.
