### ISSUE TITLE
The Scorching Heat enchantment can't be added to any tools in survival

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1844]
It's impossible to combine a book with scorching heat on it with any tool in survival. It's also impossible to add it to any tool with the Stellar Refraction Table.

**Comment by RealScubaDude** [comment]
Idk if this somehow helps but while yawing the valhelsia 3 mod, that has astral sorcery in it, I was able to actually enchant a pic with scorching heat. It stayed with me and continued to work through 3-4 updates of the mod. I took it off recently so I could try and get more of the enchantment since it couldn't be found anywhere else via trade, soul enchanter, or regular vanilla enchant table. After I took it off it could no longer be applied to any tool. I also have reason to believe that in one of the updates it turned any already existing scorching heat enchant books and turned them into blank white enchant books
