### ISSUE TITLE
Non-Bow Projectile Weapons Do Not Benefit From Projectile Speed Perks

### ISSUE THREAD

**Issue by SargeRyong** [HellFirePvP/AstralSorcery#1847]
Projectile weapons other than bows do create projectiles, and seem to be affected by projectile damage perks, but not projectile speed perks.  This includes things like Guns Without Roses firearms, Immersive Engineering revolvers and railguns, etc.

**Comment by PocketfulOfGeese** [comment]
Because the only way to track it normally would be off the onArrowFire event, which then modifies the speed.
https://github.com/HellFirePvP/AstralSorcery/blob/949c9b90f8b68e9f081af24156ec181be13e9c7a/src/main/java/hellfirepvp/astralsorcery/common/perk/type/AttributeTypeArrowSpeed.java#L37-L39

Those mods must be using their own custom code for their projectiles, and not passing the arrow fire trigger.
