### ISSUE TITLE
Attunement altar appears to work, but will not actually attune

### ISSUE THREAD

**Issue by stlcausntrbl** [HellFirePvP/AstralSorcery#1851]
I built the altar, everything looks good and it hums, threw a crystal into it because it wouldn't allow me to attune myself. I got very brief cutscene, but then the crystal went back into my inventory, not attuned.

**Comment by PocketfulOfGeese** [comment]
Only the five Bright constellations can be personally attuned (Vicio, Discidia, Aevitas, Evorsio, Armara).

If it starts then spits out, it's likely you're too close to dawn or dusk, since it only works while at night.

Otherwise, it's a mod or add-on or server plug-in conflict issue. This would be better addressed through the Discord server for live, active troubleshooting.
