### ISSUE TITLE
When using Armara and Ulteria in a Stellar Refraction Table, it will not apply Protection. (1.16.5)

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1852]
In 1.16.4, using AS 1.13.9 or 1.13.12, applying Armara and Ulteria to a piece of armour would enchant it with Protection, Fire Protection, Blast Protection, and Projectile Protection. In 1.16.5, using the same AS versions, it instead only enchants it with Fire Protection, Blast Protection, and Projectile Protection.

**Comment by Jeuvke** [comment]
The same happens with the 3 sword enchantments (sharpness, smite, and bane of arthropods) at a high level from Discidia and Vorux.

**Comment by 2468cool** [comment]
I don't know if this idea was thought of yet or if it could work, but I want to throw my hat in the ring in case this bug can be fixed.

For the time being until the bug can be fixed, what the mod could do is when an infused glass has either pair of constellations on it, it would move the effects of one constellation to another. Ulteria and Vorux can still combine everything they have on their own fine, but when paired with another it gives issues.

For an example of my idea: Ulteria and Armara are in the same infused glass, instead of Armara giving the protection, Ulteria would give it. This way gameplay-wise nothing changes from the player's perspective and everyone can use the refraction table to its fullest normally.
