### ISSUE TITLE
Crashing when trying to self attune

### ISSUE THREAD

**Issue by Rerver88** [HellFirePvP/AstralSorcery#1891]
I'm playing the [medieval minecraft](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-modpack) modpack by SharkieFPS. Note that astral sorcery is something I personally added myself and isn't part of the pack normally. I just created an attunement altar and set it to... vicio?(the 'motion' one), anyway it crashes when I try to stand on it. The game didn't generate a crashlog, so here's the regular log: [latest.log](https://github.com/HellFirePvP/AstralSorcery/files/7138795/latest.log)

**Comment by PocketfulOfGeese** [comment]
outside of a bunch of recipe errors when shutting down, and a tone of null errors from ASM patches from various mods, I don't see any crash cause. Without a crash log of some sort, nothing can be done, because the cause cannot be determined.

**Comment by Rerver88** [comment]
dang, is there any way to make the game generate a crash log somehow? Also, what are recipe errors and null errors from ASM patches?

**Comment by Rerver88** [comment]
Here's a new log: [latest.log](https://github.com/HellFirePvP/AstralSorcery/files/7143315/latest.log) which seems different from the last one. Not sure if it'll be helpful though, I don't have high hopes at this point.

**Comment by luna6667** [comment]
The crash log should be located in the "crash reports" folder

**Comment by Rerver88** [comment]
I already checked there, it isn't generating one.

**Comment by PocketfulOfGeese** [comment]
If there's no crash log, MC isn't what's crashing, it's Java instead, or something else is sending a shutdown signal. Your latest.logs look like a "clean" MC shutdown with server thread stoppages, etc.

I would recommend trying updating your Java, looks like you're still launching with 1.8.0u51, which is pretty old. Try updating to a Java8 that's u300 or higher, and making sure your launcher uses that instead of the u51 that's built-in.

**Comment by Rerver88** [comment]
That's strange, "settings" -> "apps" tells me that the version of java I have installed is "Java 8 Update 251". So unless you missed a number and meant to type u251 then something is very wrong. Well, installing the latest version is a good suggestion anyway so I'll try that first.

**Comment by PocketfulOfGeese** [comment]
nope, from the uploaded logs:
"[06:43:15] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation"

**Comment by Jeuvke** [comment]
Minecraft comes with its own bundled java version, which is 1.8.0_51.

**Comment by Rerver88** [comment]
Yeah, I was just figuring that out. Welp, I just installed the latest version of java and got Minecraft to actually use it by adding a command line argument to curseforge's Minecraft settings, but it doesn't seem to have helped. It still crashes, and still refuses to generate an actual crashlog. *sighs* Well, I've pretty much given up here. If nothing else, thanks for pointing out that my Minecraft wasn't actually using the latest version of java, I never would have figured that out myself. Thank you all for being so helpful. Unless there are any other suggestions, please feel free to close this issue thread if you want.

**Comment by TheSnowyChickens** [comment]
Guys, it is by far more worse:

https://drive.google.com/file/d/1exKm3SKiEy8qiiqgq679eruHRxXNIw6Q/view?usp=sharing
(the performance of the video is worse, yes, but you can see the black screen parts)

Just look at the video behind the link, the attunement table is 100% buggy, the cam is totally weird and no progress to the attunement.

I play a self created 100 mods pack on a server.
(no Optifine / OptiForge)

**Comment by PocketfulOfGeese** [comment]
Not remotely the same issue (so you shouldn't have placed it under this ticket), and doesn't occur with only AS.

Some other mod is conflicting with the camera controls. A list of mods would be needed, but this is better handled in the Discord, not here.

That said, if Agricraft is in your list, that's the issue since it's a bug with the needed InfinityLib, which has a fix but it doesn't appear to be pushed with an update yet: https://github.com/AgriCraft/AgriCraft/issues/1408

**Comment by TheSnowyChickens** [comment]
Yes, Agri is installed and good to know that this is fixed already.

And sry for posting it here, I just saw "attunement" and "all in" :D

I am currently not on your DC.
