### ISSUE TITLE
[Question] Is Astral Sorcery going to be updated to 1.17 or wait till 1.18 releases?

### ISSUE THREAD

**Issue by Hir0shiyt** [HellFirePvP/AstralSorcery#1896]
I just had that question because i love the fact that this is a heavy project that you have here, so i just wanted to know if it's going to be updated

[I'm not rushing you, i'm just asking]

**Comment by PocketfulOfGeese** [comment]
The discord server is the better place to ask this type of question rather than a github issues page. There is a pinned message in the #astral-sorcery channel that answers this question.

Link to the discord is available on the curseforge page for the mode, or in the readme of this github repo.

**Comment by Hir0shiyt** [comment]
Sorry then

**Comment by matyklug18** [comment]
Hello, for people who do not use Discord, would it be possible for someone to provide a copy of the message here so we are not left in the dark?

**Comment by Shadowex3** [comment]
> Goose w/an emotional support axe — 01/26/2022
> Yes, the mod will eventually be updated to 1.18/whatever version is the new modding stopping point. The mod author is very busy IRL.
> 
> This is an evergreen message. Don't be a jackass about it.

**Comment by Hir0shiyt** [comment]
Im not rushing anyone, thats why in the issue title it says "[Question]" so dont you say this is an "evergreen message"

- Thats if you where talking to me of course

**Comment by Shadowex3** [comment]
I just quoted the pinned message from the discord for people who don't use the app.

>so dont you say this is an "evergreen message"

Imagine the difference between one person throwing one pebble at a thousand people, and a thousand people throwing a pebble at one person.

That's why this is an evergreen message. Astral Sorcery has fifty _million_ downloads. If 0.1% of those people ask HellFirePvP when the mod's getting updated that's still _five hundred thousand people_.

**Comment by Hir0shiyt** [comment]
Do you even know how many of that 50M people dont uses Github and the number of people that do use it? I dont have the number but it wont even trespass the 50%
