### ISSUE TITLE
[Forge MC1.16.5] Celestial Collection Crystal Linking crash

### ISSUE THREAD

**Issue by tetrisdev** [HellFirePvP/AstralSorcery#1913]
MC Version: 1.16.5
Mod Version: astralsorcery:1.16.5-1.13.12
Forge Version: 36.2.20
Java Version: 1.8.0_202
Modpack: Stacia Expert 1.13.4

What Happened: Tried Linking Viscio Celestial Collection Crystal to a lens, structure didn't have any Starlight in it. World crashed on Exception in tick loop, in CrystalCalculations.calculate.
Whenever i try to start the server now it keeps crashing on the same error.
When first encountering the error we did have performant mod installed. Removed it and still keeps crashing
[Crash log](https://gist.github.com/dmiller2606/2478dc63ea63981399bdbe668d654d8b)

**Comment by luna6667** [comment]
You probably have a lens with no attributes on it, I don’t remember how to get rid of it though. Lenses aren’t working in 1.16.5 due to a forge bug anyways. (Not crash related though, just not transmitting starlight) 

If the lens was moved by something that wasn’t the player, ie: something that moves blocks for you, it can strip the attributes. 

Ah, found it:
To fix this, set the server config option "performNetworkIntegrityCheck" located under <pack_save_directory>/saves/<world_name>/serverconfig/astralsorcery.toml to "true" and load the game. It should resolve the issue long enough to break the lens. If not, you'll need to edit that lens out using a third party world editing tool.

**Comment by PocketfulOfGeese** [comment]
yup, lens was placed missing NBT. Don't use things like building gadgets mod to place lenses (or anything else that is NBT sensitive) and it doesn't keep the data properly.

**Comment by tetrisdev** [comment]
Placed both the Crystal and the lens of Purity II down by hand, didn't use any sort of Building tools for that. Could still have happened because of performant. Unsure though
Fixed the world by deleting Lightnetwork folder.
