### ISSUE TITLE
[1.16.5] [Iridescent Altar] Altar not charging to 100% starlight

### ISSUE THREAD

**Issue by xxo3** [HellFirePvP/AstralSorcery#1917]
No matter how many crystals or astral relays i place, the starlight level doesn't go above 90-95%
I'm using 3 maxed celestial crystals, the one above the altar is attuned to vicio and the other 2 discidia.
All the items for my custom recipe are in place correctly and discidia is not in the sky, wich should boost the amount of starlight generated by the crystals since they have the enhanced collector structure around them but it doesn't increase the starlight at all.
![2022-01-08_22 19 27](https://user-images.githubusercontent.com/97364495/148660480-7b7fb4d7-221f-41b9-a7d8-63b3cf094787.png)
Picture of my starlight setup (y=220 and in a high-starlight field)
![2022-01-08_22 19 37](https://user-images.githubusercontent.com/97364495/148660510-b2e8f517-8e49-4fc5-8606-cd5715fa9ac5.png)
Picture of altar with all 3 crystals active
![2022-01-08_22 24 56](https://user-images.githubusercontent.com/97364495/148660548-14349635-2360-4911-aefc-5cf883f3ef82.png)
Picture of altar with only top crystal active, still has the same amount of starlight.
Note: The top crystal is placed on the blue spark above the altar, as described by the astral tome to increase starlight.
![2022-01-08_22 27 53](https://user-images.githubusercontent.com/97364495/148660596-6e679e2d-0dda-4479-87ca-4e7d710b61cd.png)
Picture with only the 2 other crystals active, starlight has dropped to the same level as it would without any crystals.

The custom recipe is made via datapack and requires 8000 starlight, wich it shows as the maximum.

**Comment by PocketfulOfGeese** [comment]
Two things:
-Lenses to transmit starlight are presently bugged to not work (#1835).
-You can't actually complete a recipe in an altar that has the altar's maximum capacity as the required amount, because it's not a "set amount" when crafting, but constantly draining power during the craft and so doesn't sit exactly at max. This is not a bug, but working as intended.

You can get an altar to 100% full at night time, however.

**Comment by xxo3** [comment]
All of the pictures were taken at exactly midnight, and even only having one crystal with the enhanced collector structure as close as possible to the altar without any lenses it ends up at the exact. same. starlight.

you can also add as many astral relays as possible and it still wont increase the starlight at all past that point, although that amount of starlight doesn't appear in any recipes so it's not a huge bug.

A question, though.
Would having 7999 starlight required for the craft work since it cant be the max?

Edit: Noticed that the issue linked as duplicate included AS crafting tables as one of the blocks unable to recieve starlight, however in my testing having one crystal DID increase starlight for the altar. It's just impossible to increase it past that point.

**Comment by PocketfulOfGeese** [comment]
Yeah, it's been done more than once in 1.16.5 for illustration purposes, hence why I know it works in 1.16.5. There's a whole bunch of things going on with certain placements (diminishing returns, combination of boosting methods, starlight cannibalization, etc). Test after test after test has shown it works exactly as intended.

Regarding the 7999...It's possible, it's also highly likely no, because of the way flow values work.

Better question is "why that value?" What are you hoping to accomplish?

The discord would be better for this than a git ticket, since it's not a bug.

**Comment by xxo3** [comment]
Thank you for your response, it certainly clears things up, altough i don't understand what you're talking about with "it"

I'm trying to make the player need to essentially max out their starlight collection system to acheive creative flight by crafting the angel ring (Miniutilities)

Also if all crystal collection is bugged for altars, why would only the first crystal linked increase starlight?

**Comment by PocketfulOfGeese** [comment]
Because the crystal attuned to vicio in your images has no lens involvement. Placing it directly over the altar tends to not be a great idea in general, though. obstruction of the altar's self-collection, lack of ability to use the enhancing structure, and all.

**Comment by xxo3** [comment]
I see. Is there any way to get 100% starlight then? and how?

Thank you for the help!
