### ISSUE TITLE
Unknown crash report

### ISSUE THREAD

**Issue by KungJulio** [HellFirePvP/AstralSorcery#1947]
Been having astral sorcery crash my game for a few days now. Had some people on curseforge forums help me but they said there is nothing they can do and to report it to the author.

https://pastebin.com/yBtM1VME

**Comment by PocketfulOfGeese** [comment]
As was mentioned in the discord back on the 10th when posted there: there's no easy way to tell what's going on there, a lot of mods are modifying classes in there, and it's all vanilla MC classes reporting errors.

You'll need to perform a binary check of the mods loaded to see when having AS in solves the issue, because something is passing a null where it shouldn't.

"Instead of disabling mods one at a time, you can do a binary search. What that means is disabling half of the loaded mods at a time. If you do so and the problem persists, then you've just ruled out half of your mods as safe. If the problem goes away, then it was in the list of disabled mods. Either way we've cut your list of suspects down by 50% in a single step.

Better yet, this process can be repeated. You know which half included the problem mod, and you can disable another 50% of those, and so on. Continue narrowing it down until you find the mod at fault.

Now that's all well and good, but there is one problem. Often times mods include dependencies. When you disable a random subset of mods, you'll likely get errors that a library mod is missing, make sure not to disable a mod required by another."

**Comment by KungJulio** [comment]
Sorry for the double post, must've missed the response in the discord. I'll try the binary test search you described, however, I would like to add that the time between crashes seems very inconsistent. It will crash 3 times in 10 minutes, and sometimes once in 5 hours. Thus, I don't how to realistically carry out the test but I will try. I should also mention that I have 2 friends playing on the same modpack and both have had 0 issues. Not sure if that's relevant but thought I would at least mention it
