### ISSUE TITLE
[Question/Possible Bug] Linking Tool 

### ISSUE THREAD

**Issue by greenking13** [HellFirePvP/AstralSorcery#196]
Hello HellFirePvP, after messing around with your mod for a bit of time, I've gotten to the point in which I am attempting to make Starmetal ore. (Which is a hassle, not because of your mod, but because of a feature in the pack I am assisting with.) From what I can understand, you can use the linking tool, in conjecture with a few lens, and a starlight collector, which currently I only know of the ancient shrines crystal. After fiddling around with it, I've realized that I can't really connect the ancient crystal to anything, it says "Selected Collector Crystal", but I am unable to link it to a lens or to a block.
My question is this: Is the way you're having it be a collector tied to the crystal itself, or is it due to the location of the crystal in the shrine? I have used Blood Magic's Teleposers to move the crystal to a more desired location, and I'm wondering if that has caused an issue. (I am aware that you probably shouldn't be able to transport it, and I will most likely be notifying the head pack dev to include it on the teleposer's blacklist.)

Thank you,
Greenking13

P.S. Is there another Collector Crystal besides the shrine's crystal? I thought there might be some way to use the Starlight Crafting Altar, but so far it doesn't seem to be a thing.

Edit:
![2017-06-10_15 24 53](https://user-images.githubusercontent.com/9355993/27006067-286791c0-4df1-11e7-89a1-a41fbdbeacef.png)

I don't know how I didn't notice this earlier when I moved the crystal...

**Comment by HellFirePvP** [comment]
> I have used Blood Magic's Teleposers to move the crystal to a more desired location

you are most likely lucky that your world-save isn't corrupted yet. Moving them with unnatural means like a BM teleposer will break parts of the starlight network to a point where most things will (potentially silently) fail or just crash the server with a very likely world corruption due to out-of-sync data. This also goes for anything that is part of the starlight network (collector crystals, altar, lightwell, ritual pedestal, tree beacon, lens, prism-lens, ...)

And yes this is the way to get starmetal. link the collector crystal (potentially over the course of one or several lenses) onto an iron ore. The collector crystal will collect more starlight if it's exposed to the sky (like 90% of the mod's things that have something to do with working off of starlight)

**Comment by HellFirePvP** [comment]
Also, any means of moving a block that has a tileentity unnaturally - like BM's teleposer or 1.7.10's ThaumicTinkerer transvector dislocator - is by its nature dangerous and world corrupting. Not every tileentity stores all of its data on its NBT tag. There are many mods - such as AS - that store data along their tileentities outside of the normal world save to perform additional operations. In my case, i store starlight-network information for network-tileentities in a separate file to enable the user to build potentially big networks without having to worry about weird chunkloading issues or transmission-lag - since that is covered and cached to a point where even massive networks won't use up any tick-time.

So keep in mind, things that aren't supposed to be broken, aren't supposed to be moveable either. If you do, be prepared to face issues. I will not go out of my way to fix another mod dev's invalid assumptions.

**Comment by HellFirePvP** [comment]
As of next version, it's blacklisted for BM's teleposer.
