### ISSUE TITLE
Potential Cross Mod Issue With Ender Lillys

### ISSUE THREAD

**Issue by Skid-Inc** [HellFirePvP/AstralSorcery#203]
This video shows the issue better, but basically Ender Lillys are meant to take a long time to grow, however I can grow them almost instantly with a ritual running the Aevitas constellation. I'm going to report this to Extra Utilities as well as I don't know which side this is an issue on, or if it's considered an issue at all.

https://www.twitch.tv/videos/153244516
https://github.com/rwtema/extrautilities/issues/1541

Minecraft 1.10.4
Astral Sorcery 1.4.1
Extra Utilities 2 1.4.1
Playing on my private server sole, using the All The Mods pack.

**Comment by HellFirePvP** [comment]
Duh. Well, EnderLilies are flowers and more specifically crops. So the logic picks it up as generic crop and will fire growth ticks onto it; It treats all crops equally so idk about tema's logic on ExU. It sure is "unintended", but i wouldn't categorize it as bug...
I would say i'd wait on tema to give word on how he feels about the 'rarity' and 'effort'/time that is meant to be brought forth by the player when growing those seeds, however i'm uncertain if tema will even look at the issue on his issue tracker (judging by the numbers of issues that are left seemingly ignored)... I'll think about it, but as it stands now, it's "not really a bug, but not wanted either" - I might go out of my way to specifically nerf the interaction with certain crops at some point, but as it stands now it'll stay in there until next version at least. :P

**Comment by HellFirePvP** [comment]
Also, since i checked out parts of the whole stream recording, you've used some *pretty good* crystals there. So *that* + night + the fact that aevitas is a "major"/bright constellation and was most likely up during that night made the ritual perform *really well* - also the ritual was powered by an enhanced collector crystal so that helped aswell. It's kinda currently the most/strongest thing you can get out of AS so... yea i'm fine with it speeding up crop growth as much as it did. The crops being accelerated, as stated above, is a different matter :P

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/commit/c97792edf857a8ba3eeded580029fb4dc9d21faa#diff-720810db96955aa3f4ebb7c0dfb94a08R432

Adressed it a bit better i suppose.

**Comment by HellFirePvP** [comment]
Adressed with the 1.4.3 update.
