### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#210]
"[02:16:38] [Server thread/WARN]: Astral Sorcery loaded a new chunk (-14, 25  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config."

This does not happen that frequently, but it appears its still happening.

Happens on the latest 1.11.2 build (1.4.4)

**Comment by HellFirePvP** [comment]
For future readers of this issue: This happens because the 'bigger shrine' that spawns in mountains & cold biomes is bigger than 8 blocks in size. It spawning exactly on an edge of the 16x16 box where it could spawn then causes the adjacent chunk to load for that, solely because the structure is as big as it is. Not much i can and will do about that as rewriting would take way too much time.
