### ISSUE TITLE
[1.10.2 - 1.4.4] Skywave Resonator aren't showing anything

### ISSUE THREAD

**Issue by rinart73** [HellFirePvP/AstralSorcery#221]
I'm using Optifine. When I hold Resonator in my hand it kicks my FPS but doesn't show anything.

**Comment by HellFirePvP** [comment]
Most likely then related to optifine. How about trying without it.

**Comment by rinart73** [comment]
Sorry but I can't, I have a low end PC. And, by the way, Optifine is a default for most players.

P.C: Ok It's not related to the Optifine.
I found out that blue smoke is showing in the single player, but I can't find it in the multiplayer. Also there is no huge FPS drops in the single player. Can it be, that server tries to send every smoke particle to the client? Or something like that, I don't know how your mod is built.

**Comment by HellFirePvP** [comment]
There's practically no difference between server and client as both act as the same kind of server for the purpose of this.
The effect is calculated on clientside, the server is basically not involved in this. The only thing that the server does in this context is syncing the seed for the seeded pseudo-random initialization when the effect is first required. That might be - due to neglegible race conditions and transmission times - about 3-4 packets.

Uncertain what is causing this then. Is it spawning the particles for this at all? AS' effect handler has its own particle engine which shows the current particle count in F3

**Comment by rinart73** [comment]
I'm trying to find a spot with blue smoke on my friend's server. I'll say if I will do.

By the way, can I use this debug particle count to determine a place with good amount of stars? I'm literally stuck with the mod, because I have a tier 2 altar/crafting table and can't progress further.

**Comment by HellFirePvP** [comment]
Well you _can_ i guess. It's close to 'best' when the field has white-ish sparks in it aswell. Height is a factor too.

**Comment by rinart73** [comment]
Well I can't find a spot near me so as I placed a tier 2 altar with its structure on height 100 and it seems that a bunch of focusing relays (the ones that require lenses from aquamarine) can rise level of starlight really high up.
There is a "cannibalizing" effect that was mentioned but it's actually good cause it allows you to place a bunch of lenses high enough and then use one relay without lense to redirect starlight to the altar.
IDK was it intented to work like this or not.

**Comment by HellFirePvP** [comment]
Yes it pretty much was designed to also work that way. you can also put it higher. y>=120 yields max. amount for height.

**Comment by HellFirePvP** [comment]
Soo.. what about this issue then? I hope you're gonna add to this again if you can find a skywave field and the particles 'not showing up'.

**Comment by rinart73** [comment]
I will try today or tomorrow. But the FPS problem is confirmed. -10 FPS on really low end PC.
In comparison to fireworks or other high-particle stuff it kicks FPS really hard.

**Comment by Doomgull** [comment]
@rinart73 any update?

**Comment by rinart73** [comment]
Back then particles were not showing. I can't check now, if anything is changed after updates.

**Comment by HellFirePvP** [comment]
Most likely related to optifine or related. Try to reproduce it in the later versions for 1.12. If it persists there with solely AS and forge, please reopen this issue again. Otherwise, try play around with some of optifine's settings in regards to textures, alpha settings and so on. This is not on my end.
