### ISSUE TITLE
Shaders Issue

### ISSUE THREAD

**Issue by arlojeremy** [HellFirePvP/AstralSorcery#236]
1.10.2
Latest Optifine
Multiple Shaders tested
Astral Sorcery 1.4.5

Shaders break and this is the result: http://i.imgur.com/ALNJRzW.jpg

Removing Astral Sorcery fixes the issue. I'm assuming this is related to how Astral modifies the sky and lighting.

Crazy to think that 1.10.2 mods just really got going and now it's fractured to 1.11 and 1.12, but so be it. Don't know if this issue also effects 1.11 and 1.12.

Thanks!

**Comment by Doomgull** [comment]
Same as #124 #13 #140 

Last I heard, HellFire wasn't rewriting the shader overlay for that interaction. Using the "weakSkyRenders" config option to see if that resolves. It will result in only the constellation overlay instead of the whole sky render that way, and may fix it.

There's likely to still be particle issues with shaders that aren't addressed by that, however.

**Comment by HellFirePvP** [comment]
Yea, what doomgull said.

**Comment by arlojeremy** [comment]
Thank you.

**Comment by Flinkymeat** [comment]
doomgull, your a lazy fuckwit
