### ISSUE TITLE
1.11.2 crash with Immersive Engineering

### ISSUE THREAD

**Issue by vivagabe** [HellFirePvP/AstralSorcery#249]
I get an odd crash whenever AS and IE are in a pack together.  The odd thing is, it works fine with my computer, but with my wife's, it crashes.  I left the same report in the IE page so hopefully I can get some direction as to how to resolve.  Thanks for any help you can give!

https://paste.ee/p/aBPQt

**Comment by Doomgull** [comment]
There's a lot of initialization errors in there for more than just IE, too. Embers, etc. It threw a null-pointer just firing up the sound engine, and is spewing hatred for IE models.

I don't even see an error for AS in there.

Have her re-download the gabecraft pack, or copy your whole folder across to her, because it looks like she just has a corrupted dowload. If you added anything to the pack, verify the version of minecraft you added the mod jar for.

**Comment by HellFirePvP** [comment]
Yea i can't find any crashing reference or whatever to my mod in there, neither an indication that any of this is on my end. All messages that point to my end are debug/information messages i expect. So. yea. Not on my end.
