### ISSUE TITLE
Discidia perks

### ISSUE THREAD

**Issue by Taintacle** [HellFirePvP/AstralSorcery#254]
Currently berserk, heavy blows, and kill frenzy increase damage by a very tiny amount (5%), which is barely noticeable, especially considering that two of these perks only boost damage on a certain condition. The values of these should be increased so that they actually have an impact. And yes, I am aware these can be changed in the config, but the default values are just way too low to be noticeable.

Rooftop sniper's damage boost is way too high, as it boosts damage by a few hearts after ~15 blocks. It is also inconsistent due to the damage varying based on the distance. Also, it affects swords, even though it was meant for ranged weapons. This perk should be reworked, perhaps so that it applies a flat damage boost if the target is further than a certain distance.

Also, thorny aura doesn't seem to trigger often, perhaps the rate it triggers should be increased as well.

**Comment by HellFirePvP** [comment]
1) yes i am aware of that. I'll tend to it eventually once i finish the content parts of the next update.
2) 'even though it was meant for ranged weapons' - no, not really. It just sounds that way because i chose the name for it poorly. And no it will not be reworked.
3) iirc that is also configurable and same as 1)
