### ISSUE TITLE
[Request] Scorching Heat Config

### ISSUE THREAD

**Issue by Doragoon01** [HellFirePvP/AstralSorcery#260]
Is there a reason why this mod adds this enchantment that i'm not seeing?  Would it hurt things to be able to disable this enchant in the config file?

**Comment by HellFirePvP** [comment]
Just because you can't find a way to get it or don't know what it does doesn't mean it doesn't have a purpose.

**Comment by Doragoon01** [comment]
It's not that it doesn't have a purpose, it's that i DON"T WANT IT.  It appeared on two diamond picks in a row without me wanting it EVER.  Since i'm using other mods to ore double it's costing me resources FOR NO REASON.  It doesn't help me, and it actively hurts me.
I was asking about it having a reason for being in this mod because it's so vague about what exactly it does and how it's done that i was wondering if there was some reason for it that i don't know about because this mod's documentation is so poor.  Is there some reason to have it in the late game?  Is there some secret interaction with some other block that you're not telling us about?  I DON"T KNOW!  That's why i asked the way i did.

I've spent more time trying to figure out this mod than any other in the past year, and it's given me NOTHING useful.  But all i suggest that you could add an option so that this mod will stop activly hurting my enjoyment of other mods, and you imply that i'm stupid?  This enchantment, it's actively hurting my ability to enjoy other mods.

If you want me to find the use for it myself, i'll just go through all the code line by line, find all the secrets and easter eggs and post them all in a easy to read guide on reddit.  Nice clear guidelines of ranges of things, and what everything does should go a long way to clearing up all the confusion people are having with your mod.

**Comment by Doomgull** [comment]
How do you deal with all the other enchantments in the game? I guarantee it's not only this one you have an issue with, because quite a few enchants from mods and vanilla both are rather useless. How do you deal with those?

If anything, it wasn't implied you were stupid, it was flat out said you were ignorant. That's a lack of knowledge about the topic. Seeing as how set off this kind of thing made you though, maybe you should be seeking some counseling for your temper, though.

And part of the mod is exploring interactions and finding things. If all you want is explicit numbers, that's why the source code is visible. I doubt you'll actually go through and post a long guide fully explaining everything in the code, because you would have just checked the code instead of posting in outrage instead.

Or gone to the discord channel and asked, like most people do, and gotten assistance there.
