### ISSUE TITLE
Fluid registery question

### ISSUE THREAD

**Issue by wizard1399** [HellFirePvP/AstralSorcery#292]
Hey, 
I was having some difficulty with getting the mt for the lightwell to work, so I busted out nbt explorer to check the liquid name for starlight. The forge tegistery listed it as astralsprcery:astralsorcery.liquidstarlight"

**Comment by wizard1399** [comment]
" astralsorcery:astralsorcery.liquidstarlight " I could be wrong, but is the mod id used twice?

**Comment by HellFirePvP** [comment]
For further questions regarding the Crafttweaker integration, consider joining AS' discord server:
https://discord.gg/q37VRcT
or have a look at the amazing CT-wiki entry 'kindlich' made:
http://crafttwaeker-documentation.readthedocs.io/en/latest/#Mods/Astral_Sorcery/Astral_Sorcery/

**Comment by wizard1399** [comment]
Calls from craft tweaker scripts that deal with fluids , such as your light well, use the forge registery name to impliment the script. Since your fluid breaks convention for naming, it makes it really hard for pack makers to use. If I did not have a means of using nbt to read the registry, I would not have been able to make the script work. Just wanted to let you know.

**Comment by wizard1399** [comment]
I will include a pastebin later for you to look at when I am not connected through my phone.

**Comment by Doomgull** [comment]
...it's not breaking conventions for the registry. Fluid registry doesn't use that name. Lava isn't "minecraft.lava" in the forge registry, it's "lava", and IE's creosote isn't "immersiveengineering.creosote" but "creosote" in the registry, despite that being it's internal name.

**Comment by HellFirePvP** [comment]
Fun fact: There are no conventions. There's just "The other mods did it like that" - so idk if naming something 'creosote' is a good practice either since it also doesn't say which mod it added in the fluid registry internally. So all you're dealing with in code is "creosote" - and not something like "immersiveengineering:creosote", or "railcraft:creosote" for that matter. It's not about conventions or anything, it's about missing modid domains in the actual registry. Idk and idc how Crafttweaker wraps it. Crafttweaker doesn't define standards. Even more so if the additional data you should supply has no backing in the actual code and is thus unnecessary.
