### ISSUE TITLE
Crystal beams not showing

### ISSUE THREAD

**Issue by Fey142** [HellFirePvP/AstralSorcery#413]
**1.12.2/ Direwolf20 pack/ 1.8.3 AS version / forge 14.23.1.2555**
After going to the nether the beams disappeared even though devices were still connected (visual bug). If I break and replace they come back or unlink and link again. Sometimes happens to all sometimes to some crystals. Also breaking one crystal /mirror also makes some of the other beams magically reappear.

![image](https://user-images.githubusercontent.com/16908410/33531236-71aea4a8-d88a-11e7-93a1-9c1e76c4a062.png)

![image](https://user-images.githubusercontent.com/16908410/33531250-9735a96a-d88a-11e7-8688-d9aff1540487.png)

**Comment by Doomgull** [comment]
May be related to other nether-y issues. Check with 1.8.3 when it drops, has a possible fix for those there.

**Comment by Fey142** [comment]
The issue is still there after the 1.8.3 update.

**Comment by Fey142** [comment]
Also (Not sure if related) what I leave into another dimension and come back the lucerna ritual is disrupted and a bunch of mobs spawn (the beam from the crystal disappears though still linked) - Guessing it's more than just visual - the beam actually stops working. After the wave of monsters spawn no new ones spawn after If I stay in the area.

**Comment by Fey142** [comment]
https://youtu.be/8pNQY1B0OEc

Made a video of it. Hopefully it helps.

**Comment by HellFirePvP** [comment]
Does this only happen in conjunction with Compact machines' dimension changing method or does this happen with going to the nether & leaving it again aswell?

**Comment by Fey142** [comment]
Any dimension change - nether, mining world, twilight forest...

**Comment by HellFirePvP** [comment]
weird issue: The world still unloads eventhough certain chunks are supposed to be loaded with FTBUtils AND ChickenChunks. Seems that even those mods don't do their expected behavior?

**Comment by Fey142** [comment]
Should I report anything to them in that case?

**Comment by Fey142** [comment]
Another thing I could try is the Extra Utils chunk loader, maybe that one will work better.

**Comment by scotty9090** [comment]
Was just coming to report the same thing here.  Identical behavior as above except I've found that the entire ritual has to be reset in order to get it working again.  

I just did some testing with Discidia (since it's easier to tell if it's working than Lucerna.)  I tried various things (relinking the collector crystal, breaking and replacing the collector crystal, etc.) and although the ritual visually appears on, it does not damage any mobs.

Breaking and replacing the ritual pedestal, then replacing the crystal does seem to work, but unfortunately this requires me to redo the lens setup as well each time since the positions change so not necessarily an easy work around - maybe I'll just setup a lens in every possible position to avoid this.

**Comment by kcaffrey** [comment]
I have been experiencing this issue as well. In my case I was using an advanced charged porter from RFTools to teleport between the overworld and the mining world from Aroma1997s Dimensional World. I had the chunks containing the rituals loaded using FTBUtils on both sides, yet whenever I port between dimensions my rituals (Lucerna and Horogolium) stop working.

I'm using Direwolf20 for Minecraft 1.12, pack version 1.40, Astral Sorcery version 1.8.4.

Just like @scotty9090, breaking and replacing the ritual pedestal (and all the lens) fixes the ritual.

**Comment by jngeist** [comment]
Not a solution *per se,* since this is a mod interaction issue, but would it be possible for a redstone signal to deactivate the ritual pedestal? If so, that would be an opportunity for it to reset itself without forcing the player to replace all the lenses. It would also make it possible to send a redstone signal in a loaded chunk, such that after it's been improperly unloaded, a timer (eg) could send a signal to the ritual to restart it.

I acknowledge that this might feel hacky, except that disabling rituals via redstone seems like a legit useful feature in and of itself. It's just also a feature that would also potentially offer an opportunity to work around this issue.

**Comment by Werral** [comment]
It's not really a mod interaction issue as this happens with a vanilla dimension switch as well (i.e. nether and the end)

Cheers!

**Comment by kcaffrey** [comment]
I haven't dug into the astral sorcery code yet (I don't know a lot about minecraft mods, so I'm not sure what to look for), but if the issue as @HellFirePvP described is related to worlds unloading despite chunks being loaded, shouldn't things go back to normal when the world is reloaded? Maybe there is a problem is the world loading logic?

**Comment by Doomgull** [comment]
@werrel there are a couple different, related, issues involved. This one isn't the vanilla affected one.

**Comment by scotty9090** [comment]
At this point, I'd be ecstatic for some sort of manageable workaround solution like jngeist suggested above.  I'd even be okay with breaking / replacing the pedestal if not for the fact that I have to reset all the lenses every time (maybe if the lens position was fixed and didn't change each time?)

**Comment by jngeist** [comment]
> if the issue as @HellFirePvP described is related to worlds unloading despite chunks being loaded, shouldn't things go back to normal when the world is reloaded?

This is what happens for me, which led me to a workaround that addresses my (pretty rare) use case. If I understand right, what should happen is this: 

    Player leaves dimension -> AS is told to unload -> Chunk is unloaded
    Player enters dimension -> Chunk is loaded -> AS is told to load

But what does happen is this:

    Player leaves dimension -> AS is told to unload -> Chunkloader prevents chunk unloading
    Player enters dimension -> Chunk is already loaded -> AS is not told to load

(I'm sure that there's a gazillion things wrong with that technically, but that's about the sense I get in terms of logical flow.)

So for me, if I leave the dimension with a ChickenChunks/FTBUtils chunkloader in place, the ritual stops. If I then relog without entering the dimension, the chunk is loaded properly, and the ritual starts up again. The ritual I'm concerned about is running in its own dimension, and is fully automated. So in my case, the workaround was to leave the dimension, relog (or restart server for SMP), and then simply never enter that dimension again.

**Comment by Sorbe** [comment]
I believe I've seen something very similar to this very recently in SevTech 3.0.6 with Astral Sorcery 1.8.5 running Java 8u172 x64 in Client+Server.   ChickenChunks chunk loader in place for affected AS chunks in the overworld.  

Amara Collector crystal was set up and powering both a crafting table and a ritual altar.  The linking lines were visible to both the table and the altar.  I went to other dimensions/returned AND logged on/off.  The Collector crystal linking lines had vanished to both the table and the altar, but the table still showed full power at night and the altar was still working.  In short, it appeared to no longer be linked.

When used the linking tool, I got back the visual lines, but both devices kept working as if they had been connected the entire time.  This happened once so far.  (See screenshot after relinking fixed visual issue).

Today, when I logged back in... some of the secondary rainbow lines on my ritual altar in the overworld had vanished.  (compare with the first screenshot).

**Comment by Sorbe** [comment]
![2018-05-07_18 26 54](https://user-images.githubusercontent.com/7958470/39768530-6b07e70c-529e-11e8-9929-aafaf11029bf.png)
![2018-05-08_08 58 46](https://user-images.githubusercontent.com/7958470/39768531-6b2a1962-529e-11e8-8a7f-962c59c113c1.png)

**Comment by Sorbe** [comment]
Also, notice that the Amara constellation graphic under the ritual altar is also missing.
![2018-05-08_09 03 48](https://user-images.githubusercontent.com/7958470/39768653-d23687ee-529e-11e8-86cb-0414066ad043.png)

**Comment by Sorbe** [comment]
And the one remaining chromatic ray no long lines up with my lenses.

**Comment by Doomgull** [comment]
@Sorbe If you're still seeing this in 1.9+ versions of AS, there's a new command to aid in troubleshooting the network connections: /as slnetwork

Using it in creative mode will let you click different blocks involved and print out some debug analysis, if you could gather that output when it happens, may help to track down some things for cause. It'll likely need an imgur album because it should print out about two screens of stuff in the chat window.

**Comment by Doomgull** [comment]
@Sorbe any update?

**Comment by Sorbe** [comment]
You specifically requested no further github input from me, at al.
