### ISSUE TITLE
Special sky rendering doesn't work with the nether even if it is a void/skyblock nether

### ISSUE THREAD

**Issue by Winddbourne** [HellFirePvP/AstralSorcery#42]
My nether is a void world with no bedrock at the top or bottom. I've gone up to a height of over 300, and down below "bedrock" to the point where I've died in creative from void damage. They sky should be visible. But it's not. 

I've got the thing set to have special sky rendering for constellations but I don't see any. I also don't see the sun or moon (day night cycle) which should all be important if the nether is now actually recieving starlight. I haven't tested far enough to know if that part is working yet. It definitely is dark and red whether I set things to day or night. lol

    # Whitelist of dimension ID's that will have special sky rendering + constellation handling (and thus starlight collection, ...) [default: [0]]
    S:skySupportedDimensions <
        0,-1
     >

This is the normal hell biome. 
![2017-02-24_09 36 58](https://cloud.githubusercontent.com/assets/24589533/23307382/4fa8e696-fa75-11e6-942e-38c40b2d7aa0.png)

Here I used the terrain crystals mod to change it to a plains void island
![2017-02-24_09 37 12](https://cloud.githubusercontent.com/assets/24589533/23307383/51793192-fa75-11e6-9eca-29fa57c574a2.png)

**Comment by Saereth** [comment]
No comma in your config setting
This should work:

```
   # Whitelist of dimension ID's that will have special sky rendering + constellation handling (and thus starlight collection, ...) [default: [0]]
    S:skySupportedDimensions <
        0
        -1
     >

```
Tested to verify:
http://imgur.com/a/ghSxl

**Comment by Winddbourne** [comment]
Thanks I'll give it a try and see what happens. If it does work then I'm going to be able to do something **extremely** cool in my mod pack.  Void island control sets the nether to a 1:1 ratio with the overworld and using the World Drop mod I'll be able to let people simply fall into the nether. 

If the sky is the same, and especially the day/night cycle this transition will be extremely smooth. Also my pack is using "Fear the Darkness" which causes you to take damage in the dark. So it should enhance the day/night dichotomy I'm looking for. 

During the day you can fall into the nether, hit the bottom, and then be teleported up above the build limit of the overworld again . . . giving you plenty of time to do "/island home" or "/island spawn" unless you hit something you've built down below . . . but at night falling out of the torchlight is a death sentence. 

Going to try this now! ::grins::

**Comment by Winddbourne** [comment]
It works, though it appears to always be night in the nether. I'll let you decide if this is a feature or a bug. lol

![2017-02-24_10 16 46](https://cloud.githubusercontent.com/assets/24589533/23308864/968d987c-fa7a-11e6-8387-a674e26110a3.png)

![2017-02-24_10 16 48](https://cloud.githubusercontent.com/assets/24589533/23308867/981d8a08-fa7a-11e6-95aa-f70a5c14c909.png)

**Comment by Winddbourne** [comment]
I have confirmed that even though the moon doesn't move in the sky the moon phases do change if you stay in the nether long enough. My FPS also did recover and stay fairly stable in the 29-35 range once I stopped messing with the time.

**Comment by HellFirePvP** [comment]
The fact that it's _always night_ in the nether is because, well guess what, the nether doesn't have day or night. So essentially the skybox doesn't rotate. Hence the awkward effect that the constellations also don't move at all.

Regarding the FPS drops: Idk? It doesn't look like you had that much fps to begin with, even without the skybox.. :|

Also i'm uncertain what you want to tell me with the last screenshot there.. ? Is that a render bug caused by the non-moving skybox?...

**Comment by Winddbourne** [comment]
The first two screen shots I was getting 27-38 FPS, in the second two it was ranging from 5-29. My computer is older (I plan to update this year) so I try to keep things between 25-40 fps for me to ensure a wide range of compatibility. 

The thing that seemed like it should be a bug to me actually is the nether still not having a day or night. It makes sense when the nether is a cave dimension; and is only a little odd when we have simply removed the bedrock layers and turn it into a void with no stars, sun, or moon. However, it seems like more of a bug when we add stars and celestial bodies into the mix. 

This is one of those things where whether it is considered  a bug really is going to depend on your intentions. For example Bartz fixed the 1:8 nether ratio back to a 1:1 when he created the void world map generation. It was a nice touch and fixed a lot of multiplayer portal problems. 

Here we have an option to add sun, moon, and stars to the nether. My assumption would be that you would want to enable the day and night cycle when that happens so that the constellations rotate properly, and also so that play balance isn't messed with by having a region effected by starlight where it is always night time. 

That is also why I checked to make sure that the moon phases were actually cycling. It looks like a problem to me, but with the cycling a minor one. Whether it actually is a bug, or something to address depends on how you intend this scenario to function. 

I'm not sure if you ever thought about having the skybox enabled in a void version of the nether. :)

**Comment by HellFirePvP** [comment]
This 'kindof' got adressed with the addition of 'weakSkyRenders' as config option to basically only show constellations and not the full skyrender. It'll try and chain the previous skyrender and render the constellations on-top of that. From what i've heard, that also works/is compatible with shaders apparently.

So while this is still "odd" in the nether, one thing: the nether itself has _literally no skybox at all_. So instead of being relative to where normally the moon would be, the constellations just 'roll over' with no moon whatsoever. But well, i don't intend to change vanilla behavior. So this will not change and i'm unwilling to change it and then add tens of mod integrations that do _something_ to nether or end sky that adds some sort of moon again.

Thus, i see this as resolved to the best _maintainable_ extent.
