### ISSUE TITLE
Stars appearing dawn/dusk. Disappear at night

### ISSUE THREAD

**Issue by Zang518** [HellFirePvP/AstralSorcery#420]
Direwolf20 pack: 1.12 v1.3.0
Astral Sorcery: 1.12.2-1.8.2
Forge: 14.23.1.2555

I noticed that the stars would shine at dawn and dusk but as night rolled around, the stars would disappear. At the time of trying to figure this out, it was not raining and in a plains biome so rain will fall. Also I'm on Ep9 of DW20 series (following along closely and not getting ahead) and can clearly see the stars in his episodes. Not sure why my stars disappear at night (also kinda lonely as it's just a black blank sky). Also is this intended?

Just did a bit more testing. The stars are visible when when in single player(local machine) but not when I'm on my server.

Blank Sky
![2017-12-04_23 41 31](https://user-images.githubusercontent.com/6557762/33590714-2d748e2c-d94f-11e7-9f44-c351728ba97b.png)

Blank Sky with Moon
![2017-12-04_23 41 12](https://user-images.githubusercontent.com/6557762/33590727-3ac1b424-d94f-11e7-82fe-68b5afc241be.png)

At Dusk
![2017-12-05_00 32 07](https://user-images.githubusercontent.com/6557762/33591593-599cd892-d954-11e7-8ff3-00002a226d66.png)

A few seconds later
![2017-12-05_00 32 26-1](https://user-images.githubusercontent.com/6557762/33591609-72b2ef1a-d954-11e7-80e0-6190244bfe39.png)

**Comment by Doomgull** [comment]
Yeah, it's been mentioned on the discord server. It's not consistent among users on a server, but enabling the "weakSkyRender" option resolves it on servers, so something is fighting shader rendering.

**Comment by Bahzur** [comment]
Came here for the same issue, made a sever with a friend and hes not seing the stars either. But singleplayer they are visible.
Modlist: http://puu.sh/yAnwN/e3e180d8e4.png

**Comment by Zang518** [comment]
@Doomgull, Thanks you much for the tip. I believe I found the option. I just need to list the dimentionId such as below?
 # IF a dimensionId is listed in 'skySupportedDimensions' you can add it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render. [default: ]
    S:weakSkyRenders <
        0
>

**Comment by Bahzur** [comment]
Why did you close this issue? Its not resolved yet! Also yes thats how you enable the old render.

**Comment by Bahzur** [comment]
@Zang518 It would be better if you reopen this issue, because even though you "solved" it for yourself by using the old star render (i do too), its still an issue that exists, and the modauthors work on the currently open issues. Closing it hides it on the open list and others who encountered the same issue are likely to open thread themselves about it, which is just annoying for the authors.

**Comment by HellFirePvP** [comment]
So what? This seems to be related to some resourcepack issue or something similiar about resource loading. Not much i can do about that besides what doom already did: Suggesting the option to turn off the fancy twinkling stars in favor of actually seeing something other than a black sky. I keep track of all issues that are being opened on this issue tracker, whether i respond to them or not. In some cases i can't respond as i can't add something due to either doom already initiating the necessary steps OR there's nothing to be said since the issue is obvious and doesn't need further explanation or the solution is already known to me/i can think of something that goes wrong and the specific issue got opened because of that. If i see an issue that got closed and there's still work to do, i can reopen them myself and state the reason why. I don't see a reason to reopen it with this issue as stated above.
