### ISSUE TITLE
Conflicting mods

### ISSUE THREAD

**Issue by Zer0Lyfe** [HellFirePvP/AstralSorcery#426]
so i have testing my custom pack and happen to find a bug. The Bug is making it so i keep defaulting to a difficulty so if i select peaceful in one world it will be peaceful in another world and when you change the difficulty to normal and try reconnecting to the same world it will go to peaceful again even if you have locked the worlds difficulty.

I found out it doesn't do it on its own as it requires advanced Rocketry (its not caused by libVulpes as well) to start causing this bug for unknown reasons and if i test without astral sorcery it doesn't do the bug so it is the mods conflicting with each other

Mod Versions
Forge 1.12.2 2562
Astral Sorcery 1.12.2-1.8.3
LibVulpes 1.12.2 - 0.2.7-19-universal
Advanced Rocketry 1.12.2-1.2.6-4 (but also happen in earlier builds as well)

**Comment by Zer0Lyfe** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/981

**Comment by zmaster587** [comment]
I'm able to cause the same issue to occur with only Astral Sorcery 1.12.2-1.8.3 and twilightforest 1.12.2-3.5.263 loaded.  So I'm wondering if the issue may be Astral Sorcery plus any Dimension loading mod.  That being said it's still possible it's just Advanced Rocketry and Twilight forest have exactly the same flaw.  I'll test with a few other dimension loading mods and see if the pattern holds.

**Comment by Doomgull** [comment]
AS doesn't do anything with difficulty, though. That's what is weird.

**Comment by HellFirePvP** [comment]
The source of that issue is problematic. Original problem: If you setup multiple celestial gateways i have to ensure that the other exit-point of a gateway still exists. otherwise you basically teleport into a void or solid wall (worst case) or just where there once was a gateway. Thus, after the server started, AS scans the registered static dimension ids and does an integrity check on said dimensions to ensure that this data is correct.

Now, looking through the code for dimension loading, it seems that - eventhough a difficulty might already be set for specific dimensions, Forge just overwrites that with the default difficulty for the minecraftserver when initializing the world. Soooo..... i can't get a world object if i don't *get* it though, which causes this problem in the first place.

**Comment by Frontrider** [comment]
Also check optifine, we had a wierd graphical issue releated to that. (the corshair turned into a negative shader, after opening the journal)
Not asking for support, just noting it. We resolved it by tweaking optifine.

**Comment by Doomgull** [comment]
Optifine is known. On both sides. Theres a reason optifine says to disable certain options if you get gui weirdness.

**Comment by HellFirePvP** [comment]
#451 contains more information on this and will be the 'master' issue for this and subject to be fixed/worked on for 1.8.5 - closing this issue here - if anything need to be added, mention that on 451.
