### ISSUE TITLE
Feature Request: Tree Beacon compatibility

### ISSUE THREAD

**Issue by SynfulChaot** [HellFirePvP/AstralSorcery#435]
Would it be possible to add compatibility to the Tree Beacon for mods such as Harvestcraft to allow it to harvest more than the vanilla wood and saplings from them?

**Comment by Doomgull** [comment]
Harvestcraft fruit items are special and not part of the regular tree drops, which is why the tree Beacon doesn't Harvest them. There would have to be special handling added just for harvestcraft tree drops in order for that to function. I sincerely doubt Hellfire is going to add that.

**Comment by HellFirePvP** [comment]
This is more of an issue than a compatibility request:
1) either the tree beacon does not pick up on the tree growing -> harvestcraft doesn't fire the tree-growth events as it should (knowing the dev's capabilities this doesn't surprise me)
2) or the drops on the 'fruit' blocks are not captured since "breaking" them doesn't give you any drops, but rightclicking them when ripe does. So that is not a problem, that's just the way the other mod works.

**Comment by SynfulChaot** [comment]
The special Harvestcraft drops _are_ picked up when the block is destroyed, but only if they're 'ripe'.  The issue is that when the Tree Beacon accelerates the tree's growth, it doesn't ripen the fruit as well.

**Comment by HellFirePvP** [comment]
Yep, not gonna special-case that.
