### ISSUE TITLE
Suggestion: dim constellation whose ritual applies spectral to mobs nearby

### ISSUE THREAD

**Issue by gchpaco** [HellFirePvP/AstralSorcery#46]
Friend of mine suggested this; it's in theme for the mod, it's fantastically useful, if it's dim you don't have to deal with the player attuning to it.  Basically just applies the vanilla spectral potion effect to all mobs nearby to the ritual.

**Comment by HellFirePvP** [comment]
Just to add onto this here:

The rituals are not meant to duplicate the functionality of a vanilla beacon.
Most rituals have additional & more important features than the actual potion effect it might give you.
Just to list a few examples:
 - Aevitas: regeneration; main effect is heavily accelerating nearby crop growth.
 - Mineralis: Generates ores into nearby stone
 - Lucerna: A 'huge' magnum torch that may (depending on configuration) block every kind of natural mobspawning (meaning: not only hostile mobs).
 - Armara: resistance; main effect is reflecting all kinds of projectiles and pushing away all mobs.
[...]

True there are effects that are mainly potion effects, however i would like them not to be 'just that'.
So unless i can think of adding something to this, i will reject the suggestion, because it's 'not enough'.

**Comment by HellFirePvP** [comment]
Well, since nothing is/was suggested, i'll close this for now since just an ambient effect isn't really that useful and won't play out nicely with what Tier4 is supposed to add.

If i come up with something where the spectral potion effect fits better, sure i'd give it a go. But it's _not enough_ for a weak/"dim" constellation.
