### ISSUE TITLE
Conflict with Universal Remote

### ISSUE THREAD

**Issue by Ceriwaen** [HellFirePvP/AstralSorcery#475]
Hello!  With both Astral Sorcery and Universal Remote installed Rock Crystal Ores do not drop Rock Crystals as expected.  The ore breaks but does not provide any items.

Minecraft 1.12.2
Forge: 14.23.1.2582
Astral Sorcery: 1.8.4
Universal Remote: 0.9.10

**Comment by HellFirePvP** [comment]
In order to break rock crystal ore you have to be near it. Prevention to prevent it from being mined by quarries or related.

**Comment by Ceriwaen** [comment]
Please test.  Issue confirmed mining by hand with diamond pick fails to drop items.  Utilization of Universal Remote not required.

**Comment by Doomgull** [comment]
If universal remote simply being installed makes it not work, even if not being used, that sounds more like an issue for universal remote's tracker because they're changing something in the process.

**Comment by Ceriwaen** [comment]
I agree and reported it there as well.

**Comment by Doomgull** [comment]
Also see issue #437 , may be related.

**Comment by orbwoi** [comment]
This is being caused by the MiscUtils.isPlayerFakeMP() method in Astral Sorcery. See [this line of code](https://github.com/HellFirePvP/AstralSorcery/blob/9d2e47ea1206f0001a99730c0ef17390daa8a4b3/src/main/java/hellfirepvp/astralsorcery/common/util/MiscUtils.java#L316).

Universal Remote currently extends the player class of actual real players in order to avoid being a complicated core mod.

Unfortunately, the cannonical way developers have been checking for fake players precludes extending the base minecraft player class. See orbwoi/UniversalRemote#21 for a discussion I had with darkhax about the fake player check and object oriented programming principles.

I'm honestly curious why lines 308-317 are even needed. If they have a null connection or are not in the player list, isn't that good enough? Why care about the class being used? I've confirmed universal remote work properly with astral sorcery with them commented out.
