### ISSUE TITLE
cannot attune without constellation paper?

### ISSUE THREAD

**Issue by forestasog** [HellFirePvP/AstralSorcery#494]
i have no constellation paper and as far as i know i'm supposed to have them to do attunement.  is there any way to get them?  i saw this https://github.com/HellFirePvP/AstralSorcery/issues/235 post, but i didn't see what the solution was?

**Comment by forestasog** [comment]
o yea i forgot to put--
smp direwolf 1.12 1.40
forge 14.23.1.2566
astral sorcery 1.8.4

**Comment by Doomgull** [comment]
You have to have constellations discovered to attune to them. You gather constellation papers from dungeon loot, or from the loot chests present in all Astral Sorcery world-gen shrines (big and little, both). These can allow you to trace constellations via telescope or hand telescope. Not all constellations are discoverable until you have attuned yourself to one of the five bright constellations.

If you've lost papers of already discovered constellations and so don't know where to place the attunement relays, you can re-craft them once you've progressed into the 4th tier crafting altar, the recipes will show under the constellation in your Astral Tome.

You can also manually place the relays by looking up the relevant constellation using this handy map someone created of the attunement grid: https://codepen.io/ouroborus/full/KyREXP

**Comment by forestasog** [comment]
ok, i can do it with that map, thx :p 
also i can't make the 4th tier crafting recipe without an attuned crystal >.<

**Comment by osirisgothra** [comment]
"Leaving a comment"
There are unforeseen situations other than death when this happens. One such incident is YABBA AntiBarrels. They cannot be moved with Cardboard Boxes. True, they don't drop their own contents BUT, the average player usually errs on the side of caution OR is already moving chests in the same vicinity. The barrel errors and once placed, all papers inside are gone. This is just one of many different situations that players can lose papers by no fault of their own. It would be great if instead of papers just going blank, have them loop instead, or just do that for the lower tiers. It would save people an otherwise annoying aspect of the mod. Either that or have low-tier ritual of some sort specifically for doing just that, that would equal going to a dungeon chest and getting a paper. Lastly, but probably complicated to do, would be tracking these pages so if they disappear, they would 'reset'. oh well, that's my twenty cents (inflation, you know)!

**Comment by PocketfulOfGeese** [comment]
This issue was resolved years ago. There are recipes to create them if lost, and in 1.16 and later if stored in the tome where they should be when not in-use, they are present in any tome the player opens. Please don't reply to 4.5 year old tickets.
