### ISSUE TITLE
Ritual continues when crystal is removed

### ISSUE THREAD

**Issue by DigitalSketch** [HellFirePvP/AstralSorcery#501]
May have found a bug.  I removed my Pelotrio crystal from my ritual to stop the spawns, and it's still doing it.  

I'm running version 1.8.4

**Comment by Kuroe88** [comment]
yes, it happent to me with the one that accelerates entities. myself and zombies were buffed. But the crystal, i put it, it activated and then i took out the crystal but the effects continued. I dont know if it had anything to do but i had it with all the lenses powered up.
Also i didnt say anything because i didnt read completely how it works, i did the ritual altar just because, after that i think i deactivated it and never touch it again. 
I didnt want to say something and the reply read "emm yes thats intended" lol. but since the is other report similar, i share my limited experience.

**Comment by Doomgull** [comment]
Anything in server logs, by chance? Sounds like network isn't updating.

**Comment by Kuroe88** [comment]
in my case it was a long time ago and i dindnt pay much atention cause i wasnt using the rituals. and was a single player local game.
