### ISSUE TITLE
Can Only Interact With Lower Half Of Telescope

### ISSUE THREAD

**Issue by InsomniaKitten** [HellFirePvP/AstralSorcery#531]
Nothing happens when right-clicking the top half of a telescope, the GUI only opens when interacting with the lower half.

**Mod version:** [1.12.2-1.8.5](https://minecraft.curseforge.com/projects/astral-sorcery/files/2523583)

**Comment by SciFiz** [comment]
I noticed this too, but I couldn't remember where I'd previously been clicking to know if it'd changed.

**Comment by nikissXI** [comment]
The interface of the astronomical telescope can not be opened in the server, and the science automatically closes.My server is 1.12.2's sponge.I've changed a lot of versions of sponge.But it still doesn't work.But it can be opened in a single player game.

**Comment by Doomgull** [comment]
Irrelevant of the fact that sponge isn't supported by AS, the fix version for this clearly hasnt been pushed to curse yet, since its marked for update 1.9.

**Comment by nikissXI** [comment]
oh..all right,thinks

**Comment by Dubkatze** [comment]
Is there any workaround to the telescope not working that I can use until the next update hits?

**Comment by BigJazzz** [comment]
@Doomgull I notice that there hasn't been an update yet to address this issue (I seem unable to progress because I can't use the telescope). Do you happen to have any information on when the 1.9 version will be pushed? Sadly I'm playing FTB Revelation, so of course I'll need to wait for them to include the fixed version once it's pushed.

**Comment by Doomgull** [comment]
Hellfire had some tech issues for the last two weeks that just got resolved, so there were some delays. Unsure of eta due to this.

**Comment by BigJazzz** [comment]
Ah, no worries. Appreciate the reply. :)

**Comment by Allyraya** [comment]
My apologies for adding to a closed thread, but I do not know how to create a thread, and this issue is really bugging me, I am playing FTB Presents Direwolf20 1.12, pack version 1.10, downloaded and managed through the Twitch App. There is no record of any "Sponge" mod in my list, but I am having the same issue of where the GUI for the star map opens for a split second, then closes for no apparent reason. I would very much like to progress in A.S., but cannot reasonably do so. Many thanks for any informative replies.

**Comment by Doomgull** [comment]
The DireWolf20 pack is several versions behind on AS, which includes the fix for this issue. You'll need to unlock the pack in the Twitch launcher and manually update it to the latest Astral Sorcery version. There should be several video guides out there to accomplish this in the event that Twitch's help guide doesn't contain that information.
