### ISSUE TITLE
[Client] Crashing when attuning myself to Armara (possibly related to telepads)

### ISSUE THREAD

**Issue by MiningPickaxe** [HellFirePvP/AstralSorcery#536]
Hello,
I'm playing on a server with a custom modpack, when I try to attune and stand on the attunement altar my client crashes with the following crashlog: https://pastebin.com/XJQsKMGW This seems to be an compatability issues with telepads and the camera movement? Not sure what side causes this.

**Comment by Doomgull** [comment]
Looks like the crash is with telepads trying to save NBT data.

**Comment by HellFirePvP** [comment]
adding the cross reference here https://github.com/ArtixAllMighty/Telepads2016/issues/33

**Comment by HellFirePvP** [comment]
Closing this once he fixed & closed the issue over there.

**Comment by ArtixAllMighty** [comment]
I do must note that I can indeed initialize the field so when the class is loaded, the instance isn't null, It does get set trough a method. the field shouldn't need being accessed before that call. 
I will update it, because it is good practice to have a non null field. 
Just pointing out the mod interaction somehow saves the nbt before the data needs being accessed.
