### ISSUE TITLE
Check celestial angle instead of world time

### ISSUE THREAD

**Issue by josephcsible** [HellFirePvP/AstralSorcery#545]
Astral Sorcery should check the celestial angle instead of the world time, so that it properly supports things like permanent-night RFTools dimensions. Originally reported at https://github.com/McJty/RFTools/issues/1603#issuecomment-362397177

**Comment by Doomgull** [comment]
Why?

Besides the fact it would require a completely separate Handler in order to properly track which constellations were up in the sky versus not, it also doesn't address the fact that at least two constellations would never be seen in those Dimensions anyway because there's never an eclipse to trigger their appearance, much less moon phase changes (horologium and pelotrio, respectively).

I'm trying to think of a compelling gameplay reason why this should be done in a mod that has choices and consequences as one of the core trade-offs involved in the cases where there are choices to be made, outside of "because I wanted to work that way".

Maybe Hellfire will disagree with me now, but he had in the past stated that there would not be changes to allow constellation use in Dimensions were time did not pass.

**Comment by josephcsible** [comment]
What if Dimensions added whatever support was necessary for phases and eclipses? Would that change anything?

**Comment by Doomgull** [comment]
Its run from the world day and moonphases, separately. There's not a separate handler just to handle time passage.

**Comment by HellFirePvP** [comment]
As already discussed and explained on discord:
There is no handling for days and moonphases in minecraft. It's all done in conjunction with worldtime. Always. A day is 24000 ticks. Tick 0 is exactly dawn in a world. And the rest of the data - current time of day, current moon phase, ... - gets derived from that.
Now what does that mean for a world that's "permanently night" ? Exactly. Its worldtime has to be frozen somewhere between 12000 and 24000, potentially offset by some days x: (12000~24000) + (x * 24000).
A world where the worldtime (not totalworldtime) progresses implies a progression of the day/night cycle. If that isn't reflected in the skyrender, its just creating a invalid state of the game.

And now with your suggestion to derive that data from the current celestial angle: How the fck am i supposed to get the amount of days just looking at a number that reaches from 0 to 1 repetitively each day? Midnight at day 1 is 0.75 - midnight at day 537392 is 0.75 as far as the celestial angle is concerened (Might not actually be 0.75 but instead some other value on the 0~1 scale, but you get the point). So as far as that is concerned, i'll continue to check if it's night or not based on the way vanilla and literally all other mods that add smth like a solar panel or whatever do: worldtime.
