### ISSUE TITLE
Celestial altar not recognizing structure

### ISSUE THREAD

**Issue by dralus** [HellFirePvP/AstralSorcery#569]
Build celestial altar and structure as show in book but it is not recognizing the structure as being correct [https://imgur.com/FAaSO9K](url) [https://imgur.com/6CHf8xY](url) [https://imgur.com/kzSOasp](url) playing on direwolf20 1.12.2 version 1.8.0 on a local hosted server

**Comment by Doomgull** [comment]
That's because you built it wrong looking at the images there. Take up all the white border marble, mouse over the star in the tome so it displays the total number of each block type needed, make sure you only have the exact numbers listed there in your inventory to make it easy to tell when you've done  it incorrectly, and place the correct marble back down at the correct places.
