### ISSUE TITLE
Placed Fluid Liquid Starlight on ground, tried to pickup with bucket, World Corrupted.

### ISSUE THREAD

**Issue by Rixxaw** [HellFirePvP/AstralSorcery#582]
[https://pastebin.com/Hk7J4z7R](url)

So I was showing my son how kewl Liquid Starlight is... I put it on the ground then when I went to pick it back up with a bucket, server crashed, and I can't reload...

Not really sure if the starlight was the cause the report references astral machine.  I did link a Crystal to some iron ore before heading off to show him the fluid.  So maybe that finished and crashed the game.  It gave me a position so I'm going to try to delete the block with mC Edit.

**Comment by Rixxaw** [comment]
restored from backup played a few more hours and this morning now my restored game is crashing.  Its the same error Ticking Entity at those coords so I went into MCedit and its an AIR block above my astral stuff where I think I had a Light Well with a Aquamarine inside it before.  But that was long since used up I thought.  I just deleted it we will see.

**Comment by Rixxaw** [comment]
Okay so I figured this out, and I sure hope the Dev's are paying attention to this isssue as it will world corrupt just about anyone's world who repeats what I explain here.

My son was in here and I was showing him some Astral Sorcery.  Like checkout the Liquid Starlight ... etc I plunked down a Luminous Crafting table and showed how it filled with starlight.  I broke that table and plunked down a normal crafting table.  Etc.  I think its possible that i put the vanilla crafting table in the same exact spot as the luminous one.  Anyway i broke them both to clean the space up and I broke the floor of my Starlight crafting altar whatever to open up space for my collector below to receive starlight.  Anyway all normal stuff.

The crash indicates a position in air that is likely where the Luminous crafting table was located before I broke and removed it.  MC Edit says that the block is Air, but that it is a Tile Entity.  So either breaking the luminous table and putting the crafting table down borked the entity removal code or the server was lagging and didn't get a packet I"m not sure what happened.  The issue which the Dev's should address is why are you trying to set a boolean value on an Airblock while I'm 2000 meters away in another dimmension?

So FIgure out why your mod is corrupting my world by setting an Air Block to a Tile Entity?  Or if you can't figure that out then try checking to see if said block is still there before you tick it / set its boolean value.  Adding this simple If / then statement to your code before you tick the block would likely prevent such corruptions.  However I'm not a coder anymore, and I have no idea if any of this is possible.  However something is going on and I really hope you guys can find and fix it.

**Comment by Doomgull** [comment]
Watch your tone, don't be an ass, it'll be looked at.

Maybe find out from the Soul Stones guys what they're doing to air blocks, if you're that adamant about taking an active role in solving it.

Same crash issue as #576

**Comment by Rixxaw** [comment]
Sorry if I came off as an Ass.  I didn't mean to sound that way, I was just tired i think after 6 hours of restarting the pack and trying to locate said Airblock.  It has now happened to another person playing the same pack so you think it might be Soulstones?

**Comment by Doomgull** [comment]
AS doesnt do anything to air blocks, and soul stones IS doing something to the block and is referenced in the ticking entity both times its been reported.

**Comment by Rixxaw** [comment]
Okay well i didn't see Soul Stones in the Log but I'm not experienced with that mod or have I ever even crafted anything in it in this world.  So if the issue happens again I will remove the soulstones mod.

When I read the crash report it says Hellfirepvp.astral attempting to set Boolean value on that air block.  So that is why I came here.  I just did a search and only reference to soul anything in the log is just that soulstones is one of the mods in the pack.  Otherwise they aren't mentioned, shows how little i know about reading these things.

**Comment by Doomgull** [comment]
It's still going to be investigated under the other ticket number to see if we can't make it more resilient to outside things, so watch that one for updates.

That said, we're not doing anything there in that crash:
`Cannot set property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=astralsorcery:blockmachine, properties=[machine]}
    at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:55)`
That's an AS block value attempting to be set for an AS block, the one that's either the grindstone or the telescope, since it's the same block ID (blockmachine). But Foamfix is involved there with the "FoamyBlockState" class. The next several lines below that are Soul Stones The Old Ways being involved with their TileEntityCage class in a block (`at com.whammich.sstow.tile.*`). Rest is MC code.

In the stacktrack, it's only Foamfix and Soul Stones involved:
`Stacktrace:
    at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:55)
    at com.whammich.sstow.tile.TileEntityCage.setActiveState(TileEntityCage.java:189)
    at com.whammich.sstow.tile.TileEntityCage.func_73660_a(TileEntityCage.java:76)`

And the Block Entity being ticked is:
`  Name: minecraft:air // com.whammich.sstow.tile.TileEntityCage`

It's trying to mimic block ID 217, which should be an AS block, but it's not actually an AS block. I haven't gone through the foamfix or SSTOW code to see what they're actually doing there yet, but this is an interaction in mods causing this somehow, but it's not an AS source. Doesn't mean we can't make some sanitization checks if it's determined they're lacking, but it may not be resolved on our side. This is only the second time we've seen this issue, and both times it's happened fairly recently when no code has been changed in that block on the AS side in quite a while, so I AM curious what's happening. Again, watch the other ticket number this was duplicated to for updates when we push them out.
