### ISSUE TITLE
Shift-Right Clicking Cursed Earth from ExU2 with formation wand crashes SP

### ISSUE THREAD

**Issue by greenking13** [HellFirePvP/AstralSorcery#596]
https://gist.github.com/greenking13/e1a8f1a90d738b60f3c1cf5ecf328e50

Version: 1.12.2 1.8.5

**Comment by greenking13** [comment]
I have just learned that the bug persists after reopening the world. The wand will show being able to place cursed earth in the top left corner, and a few seconds afterwards will crash. I believe this is being caused by the preview image.

**Comment by HellFirePvP** [comment]
This is caused by Exu2 trying to load the model for connected textures for the cursed-earth on the preview rendering if you hold it in a way so the formation wand would try to render in-world blocks.
Thanks to tema's missing error handling, he doesn't check if the environment is different from what he expects and thus his handling crashes. I'll create a workaround for this, however the original issue is not on my end for this.
