### ISSUE TITLE
Automating the Altars?

### ISSUE THREAD

**Issue by q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH** [HellFirePvP/AstralSorcery#604]
I'm playing All the Mods 3, and I would like to automate the creation of ATM stars in the pack , which involves crafting something with a Celestial Altar. Is it possible to automatically craft using the altar? Or is there a separate "automatic altar"?

**Comment by Doomgull** [comment]
If the altar recipe doesn't require anything that's progression gated, you can use something that replicates player clicks with the rod to click the recipes. There's no way to automatically feed ingredients into specific slots, however, and no automatic altar, because that kind of goes against the mod intent.

Also, pretty sure atm star creation isn't something intended to be automated, so congrats on the task chosen for yourself.
