### ISSUE TITLE
[Question]what the origin of the names of those constellations?

### ISSUE THREAD

**Issue by yuanjie000** [HellFirePvP/AstralSorcery#628]
I am prepare make a Localized name for each constellations.
But wondering what the origin of the names of those constellations?
Aside from the fact that _Horologium, Octans, Bootes and Fornax_ is a reality, how do the names of other constellations come from? What do they stands for?
If you have time, I hope you can explain in detail the name of **each constellation.**
(Not native english speaker, maybe have some syntax error. )

**Comment by Doomgull** [comment]
Most of the ones without real-world counterparts were made up, mostly in pseudo-latin. Most of tanimodori's definitions are pretty close, except Vicio, which I don't recall what the source is, but is more about movement and travel.

**Comment by HellFirePvP** [comment]
As far as "Horologium", "Octans", "Bootes" and "Fornax" are concerned, those actually exist, yes. However, they don't share the same shape as the real ones.

As for the other ones, there are loose connections from each name to a specific word that is close to the "theme" of each constellation. A _direct_ translation is most likely not really possible. Most of the original words are "modified" to fit the theme of the mod as needed.

- Discidia => English "concede" + "dis" as prefix. "Dis" is often used as prefix to express the opposite of something; In this case i used "dis" in conjunction with "concede" to express an "opposite of conceding a fight".
- Armara => English "to arm". That's as much as there is to it.
- Vicio => English "vector". Math lessons are back; Any movement can be seen as a movement-vector.
- Aevitas => English "eternal" + Latin "vitas". Instead of 'eternal life', 'eternal growth' or a generally more nature-based phrasing is more appropiate.
- Evorsio => Latin "evorsio" literally means destruction.
- Mineralis => English "mineral" + "is" (Probably the least creative name)
- Lucerna => Latin "lux" + English "incinerate" (burn something, destroy). A very bright, blinding light.
- Pelotrio => Has no origin. Should express the meaning of summoning or reviving. Generally more "Necromantic" than mystical.
- Gelu => Latin "gelu"; Ice, coldness, ... - pretty straight-forward
- Ulteria => English "to attune" / "to adjust to something" - Or in this sense changing according to the surroundings
- Alcara => English "to alter" / "to change something into something else" 
- Vorux => English "voracity" / "voracious" - Has as meaning less the "greed" aspect, but rather a feral, aggressive meaning.

**Comment by yuanjie000** [comment]
Thanks for your patient, I think I probably understand.
