### ISSUE TITLE
not enough starpower in iridescent altar

### ISSUE THREAD

**Issue by salanga** [HellFirePvP/AstralSorcery#640]
I have an iridescent altar with the apropriate multiblock.
I have 2 collector crystals made from vicio attuned celestial crystal with a growth of 900 a purity of 100% and a cutting of 100%.
I have build the correct multiblock for the collector crystals with one block of space between the iridescent altar multiblock and the collector crystal multiblock and I have them linked.
even then both the collector crystals together arent producing that much power for me. they only raised the star energy bar from 20% full to 30% full. i am about 150 blocks high in a dense starfield with a lot of stars. i am already trying to make a vicio attuned resonating wand for about 7 minecraft days.
for that i need about 90% but i have no idea how i will be able to upgrade my star energy any further.
i also tried placing the collector crystal multiblock 4 blocks away from the iridescent altar multiblock.
i followed systemcollapses lead by trying to gain flight with astral sorcery in the sevtech ages modpack.
in the same starfield on the same hight i have a full celestial altar without any lenses or collector crystals.

**Comment by Doomgull** [comment]
The Spectral Relay entry in the Astral Tome discusses what happens when you place things that collect starlight too close.  

Place the collectors 16 blocks from the altar itself, and more than 16 blocks from each other. They're cannibalizing each other.

If you need more assistance, come to the Astral Sorcery Discord linked on the Curse page.
