### ISSUE TITLE
Random crash while mining with Evorsio Wand

### ISSUE THREAD

**Issue by JadeDrgn** [HellFirePvP/AstralSorcery#642]
Happens randomly, not sure why. I've been mostly mining in the Abyssal Wasteland dimension so I've only noticed the crashing there. Using the crystal pickaxe to mine.

https://pastebin.com/35Cz3zii

Forge: 2651
AS: 1.8.5

**Comment by Krapht** [comment]
My crash is most likely related (according to stacktrace) so I post here instead of creating new issue: https://pastebin.com/BYXNTNKv

In my case I was trying out a infused crystal axe. Crashed on the second tree I cut, but it was a tree farm so probably 6 or so trees bunched together.

Could it be related to quick leaf decay? When I logged back in there was still some leafs left that quickly decayed, but no log blocks

**Comment by HellFirePvP** [comment]
Will be adressed for 1.9
