### ISSUE TITLE
Book is Completely Void

### ISSUE THREAD

**Issue by PessimisticBastard** [HellFirePvP/AstralSorcery#67]
I opened up the guide book, and it is completely blank. No star formations at all. 

<a href="http://imgur.com/dC5UxFd"><img src="http://i.imgur.com/dC5UxFd.png" title="source: imgur.com" /></a>

It also doesn't allow for me to move the screen around, nor zoom in or out.

Trying to set my progress doesn't work either. The log says "Could not get progress for (my name)"

edit: Not typing in my name seems to make the command work, and I can move around the book again. However, it is still completely blank.

**Comment by HellFirePvP** [comment]
Huh... you're playing SP or on a server? It'd suggest that it failed to create a file for your research/progress

**Comment by PessimisticBastard** [comment]
I'm playing SP.

**Comment by HellFirePvP** [comment]
As originally suspected, i think something might've corrupted the progression file.. The research manager was up to now not able to really adress this and, well, now in regards to #87 i've changed that a bit and created a backup-file system as well as a mechanism that should prevent this - In case this actually is progression loss due to a corrupted file; and it looks that way to me.. Regardless, this is most likely adressed...
