### ISSUE TITLE
Waila/Hwyla Support in 1.12.2

### ISSUE THREAD

**Issue by Keridos** [HellFirePvP/AstralSorcery#690]
Just wanted to ask if you could integrate some basic support for Waila/Hwyla for this mod. Some blocks could show their status like multiblock formed right or starlight available in the tooltip shown by Waila.

**Comment by Doomgull** [comment]
Starlight available isn't meant to be player-seen, because it has no context for the values to make sense.

There's a tool coming in 1.9 to show multiblock construction errors, which is already indicated by a lack of particles or a giant Red Bar inside the GUI of the altar. This really isn't something that should be in a waila/hwyla tooltip anyhow.
