### ISSUE TITLE
Should tree beacon trees have leaf decay?

### ISSUE THREAD

**Issue by ruifung** [HellFirePvP/AstralSorcery#779]
I find it strange, since lore-wise the tree beacon harvests bits and pieces  when the tree grows, but the tree is gone and all thats left is a few blocks of leaves seperated in mid air.

Perhaps isolated leaves should be removed faster (i.e something like leaf decay.)

**Comment by HellFirePvP** [comment]
Due to the fact that this aims to be compatible with anything that is basically firing a event describing that a tree is growing - which is just a collection of blocks - i can't define what's a leaf and what's not on a reliable basis. For this to be implemented in a proper way, Forge might need to actually finally include a form of tree-registry where proper sapling, log and leaf blocks as well as a respective generator are defined. However, said thing has been denied in the past twice already for whatever reason, so as there is no proper way to determine if a block is a leaf or not, i can't implement a proper algorithm that would capture this on a reliable basis.
