### ISSUE TITLE
Phoenix Fire Voids Baubles

### ISSUE THREAD

**Issue by robotbrain** [HellFirePvP/AstralSorcery#817]
Reported by a player on my private server running DW20 1.12, a player was brought back with phoenix fire and in the process all baubles disappeared. Issue happened twice with only log entries around the issue's occurrence being warnings about a different player moving too fast. AS 1.12.2-1.9.3, Baubles 1.12-1.5.2 as per latest release of DW20 1.12

**Comment by Doomgull** [comment]
So, it actually doesn't.

This has pretty extensively been tested, actually, and fairly recently.

This needs to have a ticket opened with the Grave Stones Mod guys, since they're using HIGH priority on their death trigger instead of something sane, like LOW or LOWEST since they should listening for outcomes, not trying to capture people's fucking items before another mod does.

"// Hopefully ensure we capture items before other things do (set to high so other mods can run before if they have more specialness
    @SubscribeEvent(priority = EventPriority.HIGH)"

**Comment by HellFirePvP** [comment]
To add on to this:

> capture people's fucking items before another mod does.

The purpose of a grave-mod is to capture the outcomes. not the items "coming in to the death cycle". If another mod captures & saves an item before the grave is supposed to pick it up, it's purposefully done. Potentially a mechanic like soulbound listens to the death event to remove the soulbound' items from the players inventory preemtively to add them back to the player when it respawns. A grave mod capturing the items *before* that would make any functionality like that fail outright. If a mod decides to capture & remove items before the death event is over, it is done purposefully to achieve some sort of other outcome that is (in a VERY general sense) "Different from just dropping the items when the player dies". Grave mods should account for that. Apparently some developers just don't get how mod interactions are supposed to work. A mod being popular doesn't mean the developer is good.
