### ISSUE TITLE
Emissive Textures on Entities and Optifine

### ISSUE THREAD

**Issue by Liamdude** [HellFirePvP/AstralSorcery#827]
I know from the Curse page that there are issues with Optifine, but I have an issue I am posting on both issues pages nonetheless. The issue that is that after adding Astral Sorcery to my mod list, it crashes my game when using emissive textures on entities as part of a texture pack. The game does not crash with emissive textures on items or blocks, just on entities. Additionally, when there are emissive entity textures, the game will crash on some items which do NOT have emissive textures at all. I have included a crash log showing an example of both situations. One is a crash on the alchemical chest from ProjectE (to which I added an emissive texture), and the other is from a Quark chest which does not have an emissive texture at all. Help would be appreciated, and thank you in advance.

[crash-2018-07-26_21.44.38-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2234202/crash-2018-07-26_21.44.38-client.txt)
[crash-2018-07-26_21.59.38-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2234203/crash-2018-07-26_21.59.38-client.txt)

**Comment by Doomgull** [comment]
Astral sorcery isn't even listed in either of those traces. Its all null pointer exceptions from optifine.

What makes you think this has anything to do with AS?

**Comment by Liamdude** [comment]
Forgot to mention that: I wiped my mod list and added mods back one at a time. When I added AS back, it finally reproduced the crash. I tried adjusting config settings and trying again, but the crash kept occurring. Then I removed AS and the textures reappeared and there were no crashes. Now I have recreated my full mod list without AS and everything is working fine. I even tested re-adding AS to the full list, and it only crashes when AS is present.

**Comment by Doomgull** [comment]
Can try using the weakSkyRender config option, but that's about as far as this will ever go on AS's side, especially since AS isn't in the trace at all: 

Shaders or other features of Optifine are known to cause graphical issues. Due to the lack of collaboration of anyone of the Optifine team and the fact that Optifine's sourcecode is not visible, issues regarding that can't be tackled at all. Use shaders or other features of Optifine at your own risk! (With issues in regards to skyrendering being absolutely broken, check out the config option "weakSkyRender" and add the dimension-ids where AS skyrendering shouldn't be done in order to make it "somewhat compatible")

**Comment by Aer-ink** [comment]
I can confirm that the isssue only happens when astral sorcery I tried it out with an instance that only contains Optifine, AS, and Aether legacy (for the emissive textures) installed here is another crash report hopefully it will contain more info about it if it is not on your side I might try to contact Optifine devs to report it 
https://paste.ee/p/bp4wc
