### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by darkshadow543** [HellFirePvP/AstralSorcery#85]
Whilst searching for deep constalations, I traced out a patteren in one of the pictures, shown here, and it didn't recognize the constalation. Am I missing something or what?  Using the most recent 1.11.2 version.
![2017-03-25_20 36 43](https://cloud.githubusercontent.com/assets/14943673/24327301/9e58e61e-119b-11e7-826a-a682d65625ec.png)

**Comment by HellFirePvP** [comment]
You're most likely missing progression - There is at the moment the inconsistency that you can see the constellation & get the constellation paper, but you're unable to match it in the telescope gui due to missing progression. Attune yourself to a constellation via attunement altar and you can then discover those - That's still kinda awkward, but progression is in the process of being overhauled so hopefully stuff like this doesn't come up in the future...

**Comment by darkshadow543** [comment]
Thanks
