### ISSUE TITLE
Evorsio Static Charge Perk can destroy baubles / kill player twice

### ISSUE THREAD

**Issue by triacontakai** [HellFirePvP/AstralSorcery#853]
I shot a friend with a very powerful tinker's construct bow, which instakilled them and had the Static Charge perk trigger at the same time: 
![image](https://user-images.githubusercontent.com/31161627/44432839-b288d700-a571-11e8-9952-1ae3f84a062a.png)
Upon respawning, they had no baubles on them or on their grave.

AS Version: 1.9.4
Forge Version: 14.23.4.2739
Pack: Engimatica 2 Expert 1.34

**Comment by HellFirePvP** [comment]
Which grave mod are you using, which version of said mod?

**Comment by triacontakai** [comment]
Tomb Many Graves: 1.12-4.1.0
TombManyGraves2 API: 1.12-1.0.0
TombManyPlugins Backpacks: 1.0.0
TombManyPlugins Cosmetic Armor: 1.0.0

**Comment by Doomgull** [comment]
Out of curiosity, what are the stats and material abilities of that crossbow?

**Comment by Darkmega18** [comment]
Not sure about it being related, but there was some twilight forest related bauble destruction shenanigans going on at one point. you wouldn't happen to have it would you? Since my last two packs have had it and I've had similar bauble destruction on death issues due to it and something to do with it's charm of keeping keeping the baubles stored away or something. Although I've also got other things like revive mods possibly interacting with it.

The baubles usually pop out of you when you relog but you end up passing it off as they got deleted and so just get new ones or cheat them back in due to glitch when they're just bugged invisible. :V. and the latest update for twilight forest should have fixed it I believe.

**Comment by triacontakai** [comment]
Enigmatica 2 Expert does have TF, but we both have no TF items in our inventory anywhere (not even in backpacks)
We've killed each other a countless amount of times, this issue only happened after the weird double-death shenanigans.

**Comment by Doomgull** [comment]
Yeah, if there's a double-death, not a whole lot we can do there because it's firing events in a weird fashion, and anything interacting with the death event is going to do weird things. Perhaps check in again after 1.10's perk overhaul drops and see if it's still occurring, but...

**Comment by terrapin47** [comment]
Twilight Forest's bauble code should be fixed in the latest version, so updating that might solve the issue with losing them at least.

https://minecraft.curseforge.com/projects/the-twilight-forest/files/2605275

**Comment by Doomgull** [comment]
@triacontakai still occurring with the new perk system?
