### ISSUE TITLE
Respendant Gem mod Interactions

### ISSUE THREAD

**Issue by darkshadow543** [HellFirePvP/AstralSorcery#854]
Basically, it appears that the Resplendent Gem has trouble working with some mods, such as random things.  Crashes on start.
MC: 1.12.2
Forge:14.23.4.2757
Astral Sorcery: 1.9.4
Random Things: 4.2.1
[crash-2018-08-25_15.31.31-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2320988/crash-2018-08-25_15.31.31-client.txt)

**Comment by Doomgull** [comment]
Looks more like the ender bucket doesn't like having it's stack size looked at.

**Comment by HellFirePvP** [comment]
randomthings is not checking if the itemstack in question already has the capability added or not. due to the fact that capability gathering happens before full itemstack initialization finishes, this data is incomplete.
randomthings initializes its capabilities very late and not through the normal way (overriding hasCapability and getCapability); see https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/item/ItemEnderBucket.java#L69
So. Not on my end.
