### ISSUE TITLE
Suggestion : Chalice Alternatives

### ISSUE THREAD

**Issue by jgizle** [HellFirePvP/AstralSorcery#883]
On most servers the chalices end up getting banned due to causing server lag. This causes some issues with progression in the mod. For example having to waste 12 buckets of star liquid to craft any tools with rock crystals vs being able to craft like a dozen for the same cost. This means having to farm significantly more rock crystals and aquamarine shale throughout the mod for the same amount of progression. This also means you cant use evershifting fountains which would normally be allowed in mining worlds and such.

It would be amazing if the chalices could be substituted for any tank or liquid holding block within a radius. Unless you know a way of reducing the lag the chalices produce (from their ability to react with one another and create blocks that just randomly spawn and fall on the floor).

**Comment by Doomgull** [comment]
First I've heard of lag from them. Do you have any profiling, or is it literally just the "lots of items created" thing?

You DO realize if you apply a redstone signal to them (as mentioned in the Tome) they won't create blocks, right?

Also...why does it cost 12 buckets to make tools? Something doesn't add up here.

**Comment by Doomgull** [comment]
The Tome mentions the redstone, so crafting one shouldn't matter.

Excepting the crystal tools, the Infuser should use, with stock recipes, at most one block of starlight. And there's a chance it won't use any. The Crystal Tools are a special case exception to this, that is intentional to consume all 12 blocks.

Should check with the owner for why they banned chalices. If it was for some other reason besides people being irresponsible and leaving huge chunks of loose items around, would be good to have a visualvm sample of it in action, because I've never seen that excepting one very old issue caused when placing them with only a single block separation.

**Comment by Doomgull** [comment]
Also...split your crystals. You get far more liquid starlight when the lightwell is provided more starlight to begin with (especially if linked to a collector), and longer life from crystals that are higher in the "food chain". Aquamarine provides just enough to get you going. A celestial crystal, or an attuned rock or attuned celestial, will provide far more liquid starlight than it takes to make them, much less grow them to maximum size and cause them to split.
