### ISSUE TITLE
[1.12.2] Server Crash - hellfirepvp.astralsorcery.common.event.BlockModifyEvent.getWorld

### ISSUE THREAD

**Issue by MokahTGS** [HellFirePvP/AstralSorcery#908]
Getting a server crash when it seemed to try to generate a new chunk.

Forge 2768
AS 1.12.2.1.10.3
Full mod list: https://pastebin.com/tVchktpi

Server Crash Log: https://pastebin.com/VMTUpqid

**Comment by HellFirePvP** [comment]
Hm.. this seems more like just happened to happen when AS was doing stuff..
After all, it literally only called a getter at that line and not any complex/large calculation or whatever: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/event/BlockModifyEvent.java#L50

So... seems more like chunk generation cascading into more generation, ultimately having the server generate/load a lot of chunks causing the watchdog to kill the server since it didn't "tick" another time after 60 seconds had passed. Not really sure this is/was on AS' end.

**Comment by MokahTGS** [comment]
From the log right before it crashed:  https://pastebin.com/EP0YZm44

It's calling out Thaumcraft, Roguelike Dungeons, and Biomes O Plenty with runaway chunk generation, but then the crash log that happened calls out AS, probably for the reasoned you mentioned.  I'm ot sure how to get this fixed.

**Comment by Doomgull** [comment]
I have seen where roguelike is not included in during Overworld pre generation, and then it's added back in for additional Dimensions to generate on their own. So if it does crash out, hopefully should only drop that other dimension, and not everything.

Otherwise, you might need to play with the roguelike configurations, so that they're perhaps less dense.

**Comment by MokahTGS** [comment]
The issue is that this seems to be a new thing that hasn't been a problem on our server before.  Our configs for Roguelike Dungeons is old enough to know that the density hasn't changed between worlds where this happens and worlds where it doesn't.

Something has changed in the last year that is now causing this.  I'm trying to see if we can all find the culprit and get it fixed.  I'll reduce the frequency of the dungeons, but truth be told, my gut says that isn't it.

**Comment by Doomgull** [comment]
Honestly, it is likely a whole bunch of little things that keep chaining each other. So individually it won't be a problem, but then you hit one point where they happen to converge and it keeps firing off over and over again. Out of the list of world gen mods, roguelike is the one with the largest footprint in the world, other than worleycaves. It might be something changing between those two combined with something else? Maybe something's not properly being centered it at chunk for thaumcraft and so is triggering duplications, everything else in that list I'm pretty certain sits within a single chunk or properly sanitizes itself though. I might be wrong and have missed something.
