### ISSUE TITLE
There are currently two perks tabs in the Astral Tome

### ISSUE THREAD

**Issue by MartyGentillon** [HellFirePvP/AstralSorcery#923]
As of the Nov 27 Jenkins build, the Astral Tome contains two tabs labeled perks.

**Comment by Doomgull** [comment]
Already fixed in dev. Stop reporting bugs from test builds.

**Comment by MartyGentillon** [comment]
The Jenkins build theoretically are dev... but ok.

**Comment by HellFirePvP** [comment]
Yes. They are dev. _In-dev_. Not even alpha.
These builds are now public and readily downloadable thanks to my patrons, however are meant for people that wait on critical features, such as CraftTweaker integrations or other small fixes, to continue their pack development seamlessly without having to wait until a new release build is out. You may use those builds to see what's being worked on, no problem, but bugs such as "misses texture" or "doesn't have localization" are expected because, well, it's _in active development and unfinished_.
Don't report bugs on those builds. Thanks.
