### ISSUE TITLE
[Crash] when upgrading altar to teir 3 (Celestial Altar)

### ISSUE THREAD

**Issue by NightmareTwilight** [HellFirePvP/AstralSorcery#959]
I crashed when trying to upgrade the Starlight Crafting Altar to the Celestial Altar, while I didn't have a problem with the previous one. Tried to enter the world again, blocks apeared to have changed. I crashed soon after, again.

Crash: https://paste.dimdev.org/ojavolutux.mccrash

**Comment by Doomgull** [comment]
Looks like your altar block has an issue with the nbt on it. Break it so it isn't in the multiblock, make another, let me know if it replicates.

**Comment by mastio** [comment]
Hello, I had the same crash with the egnimatica 2 expert last update. I just place a spectral relay on the attunement altar and the game crash and corrupt the save. I made sure that a replace the altar before doing this.

I think there is an issue with the updated multiblock checker.

**Comment by Doomgull** [comment]
Have you broken the multiblock and reformed it, and was it using the same altar?

**Comment by Nagapito** [comment]
You sure this is fixed? 

Enigmatica 2 Expert updated from 1.46 to 1.49, which already have the latest version of Astral Sorcery and had the same issue.... All world  is corrupt...

**Comment by Doomgull** [comment]
@Nagapito does it include AS 1.10.10?

**Comment by Nagapito** [comment]
Yes astralsorcery-1.12.2-1.10.10,jar

**Comment by Doomgull** [comment]
@Nagapito per my second request up above, need a pastebin of the crash.

**Comment by Nagapito** [comment]
I can give you a crashlog but it will show nothing since the crash is not directly related to your mod
here: https://termbin.com/vz8ks    

The world is crashing randomly because now this is his state:
https://imgur.com/a/6XLjGZW
I managed to make it load by disabling all chunkloading and my base was not crashing....

**Comment by Doomgull** [comment]
"java.lang.ClassCastException: zmaster587.advancedRocketry.block.multiblock.BlockARHatch cannot be cast to appeng.block.crafting.BlockCraftingUnit"

It's entirely coincidence. AS multiblock code, like all mods, has zero impact on the multiblock code of other mods. Needs to be reported to the Adv Rocketry devs.

**Comment by Nagapito** [comment]
The thing is, it is crashing because what used to be a block from AE now is a random block from Adv Rocketry due to blockID corruption in the level.dat.  

How this level.dat corruption happened? Could be anything but, seems your mod was causing blockID corruption and you fixed it in the latest version. 
I am just calling your attention to this coz it might not be totally fixed and might still be causing level.dat corruptions.

**Comment by Doomgull** [comment]
No, it was not causing blockID corruption. It was causing a crash. The crash can cause corruption if the server doesn't handle things cleanly, which is a risk with any crash.

Unless you have a crash log from the original crash post upgrade that caused the world to become corrupt, showing it was AS triggering it and the method, so it can be investigated for possible recursion of the issue, then it was either not AS, or it doesn't matter because no logs to give information. Chasing "possible maybe perhaps" ghosts will not be happening.

Issue closed unless there's a useful log from the original crash.
