### ISSUE TITLE
Crashed caused by bad Data in AstralSorceryData!

### ISSUE THREAD

**Issue by KaneHart** [HellFirePvP/AstralSorcery#977]
So I posted this as a bug a few days ago under #973 and I was told this seems to be a EU2 issue not a AS issue.

So what I ended up doing was nuking EU2 and then loading the world up and it ran fine but then I added EU2 back and it crashed...

So I did the same thing with AS and same results....

So I deleted the EU2 Data File and still crashing...

So what I did was renamed EVERY single Region / world in the world folder...

Still Crashed.

So I decided to nuke AS Data folder... And guess what? Server is back online and working just fine.

As much as this was blamed on EU2 the bad data clearly sitting in AS Data folder.

I'm sure deleting AS Data folder is not the best thing ever but what else could I do.. I have a backup for now maybe I can restore it later on once this issue is fixed.

https://pastebin.com/mZQAGc6k

**Comment by HellFirePvP** [comment]
Exu2 issue. Again.
It's an issue in their deserialization. That's _it_. This is not my fault.

**Comment by valarnin** [comment]
I realize that this is a problem with ExU2's deserialization, but I feel the need to point out that the code block in question in AS is catching the base Exception class and throwing away the exception, which isn't exactly good practice and maybe should have a debug or warning logged? It wouldn't help in this case (wouldn't catch the AbstractMethodError, since that extends from Error and not Exception), but still strikes me as wrong as a Java dev (though not a mod dev).

Just something I noticed earlier before the issue was closed.

**Comment by valarnin** [comment]
Sorry, I think maybe I phrased something badly there.

I wasn't suggesting you catch the Error that's being thrown, but instead that you should log the Exception that could be caught (even though it's irrelevant to this issue, since the issue in question is throwing an Error and not an Exception).

Again, I'm a Java dev, not a mod dev, so maybe there's Forge standards for exception handling that I'm not aware of, but generally speaking it's bad coding standards to catch an exception and then do nothing with it.
