### ISSUE TITLE
[Question] My attunement multiblock isn't working?

### ISSUE THREAD

**Issue by slfrench2** [HellFirePvP/AstralSorcery#99]
I have created the attunement multiblock, but the sooty marble hasn't changed or isn't glowing anywhere like in the video I watched from Vallen. Not sure if I'm doing something wrong or if I need to wait for a different constellation or what. Does the multiblock also need to be in the smokey area shown by the resonator?

**Comment by HellFirePvP** [comment]
You'll see if you built it correctly when the little white sparks appear right on top of the sooty marble; So that's the first thing to look out for. That doesn't require any constellation or something, it's just the sign that the altar recognizes the multiblock as complete and that it can see the sky at all positions of the sooty marble.
Send a screenshot of your setup if that doesn't work..

**Comment by slfrench2** [comment]
Issue was resolved when rebuilding structure. I'm sure I built it correctly the first time but maybe I didn't or there was some sort of de-sync. Anyways the structure works now. Thanks for the help anyway. Btw love your mod

**Comment by HellFirePvP** [comment]
Uhhhh.. Alright? If you experience any crash or bugs related to the mod, don't hesitate to open another issue ;)
